

CURRENT_ALBUM = "祈愿树林.jpg"

ASS_VIDEO_GENERATOR_PATH = 'E:\\AssVideoGenerator'

GENERATE_VIDEO_PATHS = [
    "output/audio/Animation/FreshSoveign",
    "output/audio/Combat/Qiyuanshulin_MutantVine",
    "output/audio/MusicSFX",
    "output/audio/Online/1.0_OBT/Animation_LS_Qiyuanshulin",
    "output/audio/Online/1.0_OBT/Boss_Qigda",
    "output/audio/PLOT/plot4_1",
    "output/audio/PLOT/plot4_2",
    "output/audio/Scene/Map04_QiYuanShuLin"
]

FILE_MAP = {
    'Silence Wav.wav': '',
    'BGM_LS_ClothingEvolution_Butterfly_ChangeBPM.wav': '',
    'BGM_LS_ClothingEvolution_General_1.wav': '',
    'BGM_LS_ClothingEvolution_General_2.wav': '',
    'BGM_LS_ClothingEvolution_S0062_Goldenrose.wav': '',
    'BGM_LS_ClothingEvolution_S0128_SilverNightingale.wav': '',
    'BGM_LS_ClothingEvolution_S0145_SeaSpray_Dress.wav': '',
    'BGM_LS_ClothingEvolution_S0161_DreamElf.wav': '',
    'BGM_LS_ClothingEvolution_S0165_Jingying.wav': '',
    'BGM_LS_ClothingEvolution_SpringFlower_v2.wav': '',
    'BGM_LS_ClothingEvolution_SwanLake_3.wav': '',
    'General_Fresh.wav': '',
    'Bgm_CoolSovereign_Appear.wav': '',
    'Bgm_CoolSovereign_Battle.wav': '',
    'Bgm_CoolSovereign_Battle_Fail.wav': '',
    'Bgm_CoolSovereign_Battle_Success.wav': '',
    'LS0100_SC123_ChangeBPM_0708.wav': '',
    'LS0100_SC126_ChangeBPM_0628.wav': '',
    'LS0100_SC127_ChangeBPM_0628.wav': '',
    'LS0100_SC128_ChangeBPM_0628.wav': '',
    'LS0100_SC129_ChangeBPM.wav': '',
    'LS0100_SC121_BGM.wav': '',
    'Bgm_FreshSoveign_Success.wav': '清新天王 | 获胜',
    'Bgm_FreshSovereign_Battle_Fail.wav': '清新天王 | 失败',
    'Bgm_FreshSovereign_Battle_Perfect.wav': '清新天王 | 完美',
    'Bgm_FreshSovereign_Battle_v1.wav': '清新天王 | V1',
    'BGM_ui_summon_loop_bpm208_m34.wav': '',
    'BGM_ui_summon_lucky_intro_bpm208_m34.wav': '',
    'BGM_ui_summon_normal_intro_bpm208_m34.wav': '',
    'LS_Resonance_Performance.wav': '',
    'BGM_Animation_ShiShuTian_GhostTrainFirstTime.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC201.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC202.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC203.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC204.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC205.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC206.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC207.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC211.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC213.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC214.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC215.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC220C_Master_Intro_146_4_4.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC220C_Master_Loop_146_4_4.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC220D_Master_Oneshot_146_4_4.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC220E_Master_Oneshot.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC220_Master_Intro_146_4_4.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC220_Master_Loop_146_4_4.wav': '',
    'BGM_Animation_ShiShuTian_LS0100_SC222.wav': '',
    'BGM_Animation_ShiShuTian_LS_ShowGlideRoute.wav': '',
    'BGM_Animation_ShiShuTian_LS_TreeHeartWater_01.wav': '',
    'BGM_Animation_ShiShuTian_LS_TreeHeart_01.wav': '',
    'Mirror_Challenge_Battle.wav': '',
    'Mirror_Challenge_Battle_Fail.wav': '',
    'Mirror_Challenge_Battle_Success.wav': '',
    'Bgm_Animation_1_1_LS_CS20_SC027_124_3_4_KiloAppear_MixV1.wav': '',
    'Bgm_Animation_1_1_LS_CS20_SC028_HarpShow.wav': '',
    'Bgm_Animation_1_1_LS_CS20_SC028_HarpShow_AddPiano.wav': '',
    'Bgm_Animation_1_1_LS_CS20_SC030_DragonLeave_MixV1.wav': '',
    'Bgm_Animation_1_1_LS0100_SC010_DownHill_VNTA.wav': '',
    'Bgm_Animation_1_3_LS_CS20_SC005_FishShow.wav': '',
    'Bgm_Animation_1_3_LS_CS20_SC006_End.wav': '',
    'Bgm_Animation_1_5_LS_CS20_SC010_WishGoblin_230629.wav': '',
    'Bgm_Animation_3_1_LS0100_SC212.wav': '',
    'Bgm_Animation_Prologue_LS0100_SC002.wav': '',
    'Bgm_Animation_Prologue_LS0100_SC007.wav': '',
    'Bgm_Animation_Prologue_LS0100_SC008_P1.wav': '',
    'Bgm_Animation_Prologue_LS0100_SC008_P2.wav': '',
    'LS0100_SC001_bgm.wav': '',
    'LS0100_SC004_bgm.wav': '',
    'SingingDragon_QiYuanShuLin_LS0100_SC115P.wav': '',
    'SingingDragon_QiYuanShuLin_LS0100_SC115Q.wav': '',
    'SingingDragon_QiYuanShuLin_LS0100_SC115R.wav': '',
    'SingingDragon_QiYuanShuLin_LS0100_SC115S.wav': '',
    'SingingDragon_QiYuanShuLin_LS0100_SC115T.wav': '',
    'SingingDragon_QiYuanShuLin_LS0100_SC115U.wav': '',
    'SingingDragon_QiYuanShuLin_LS0100_SC115V.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC011.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC012.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC012_HeartBeat.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC013.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC014.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC015.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC016.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC017.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC018.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC026.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC027.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC030.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC032-062424.wav': '',
    'Bgm_Animation_WishTown_LS0100_SC034_v2.wav': '',
    'BGM_Boss_TanLanQiuNiao_EndingLS_98_4_4.wav': '',
    'BGM_Boss_TanLanQiuNiao_Intro_Loop_98_4_4.wav': '',
    'BGM_Boss_TanLanQiuNiao_P2_98to106_4_4.wav': '',
    'BGM_Combat_General_Intro_V1_5_4_164.wav': '',
    'BGM_Combat_General_Intro_V2_5_4_164.wav': '',
    'BGM_Combat_General_Intro_V3_5_4_164.wav': '',
    'BGM_Combat_General_Intro_V4_5_4_164.wav': '',
    'BGM_Combat_General_Loop_164.wav': '',
    'BGM_Scene_Qiyuanshulin_Combat_MutantVine_bpm78_m44.wav': '变异树藤 | 战斗',
    'BGM_Scene_Qiyuanshulin_Normal_MutantVine_bpm78_m44.wav': '变异树藤 | 正常',
    'BGM_Battle_Stoneboss_Step1_125_4_4.wav': '',
    'BGM_Battle_Stoneboss_Step2_Intro_130_4_4.wav': '',
    'BGM_Battle_Stoneboss_Step2_Loop_130_4_4.wav': '',
    'BGM_Battle_Stoneboss_Step2_Outro_130_4_4.wav': '',
    'BGM_CleanAnimal_End_80_4_4.wav': '',
    'BGM_CleanAnimal_Loop_80_4_4.wav': '',
    'BGM_System_ClothingDisplay_New_General_Lose.wav': '',
    'BGM_System_ClothingDisplay_New_General_Main_110_3_4.wav': '',
    'BGM_System_ClothingDisplay_New_General_Win.wav': '',
    'Bgm_Fishing_Normal_L3_Full_New.wav': '',
    'BGM_LegendAnimal_Swan_End_65_4_4.wav': '',
    'BGM_LegendAnimal_Swan_Loop_65_4_4.wav': '',
    'BGM_LegendAnimal_Swan_Loop_Bell_1_65_4_4.wav': '',
    'BGM_LegendAnimal_Swan_Loop_Bell_2_65_4_4.wav': '',
    'BGM_LegendAnimal_Swan_Main_65_4_4.wav': '',
    'BGM_LegendAnimal_Swan_Soar_65_4_4.wav': '',
    'Bgm_LS_DelicateSwan_Performance_Meet.wav': '',
    'Bgm_LS_DelicateSwan_Performance_Takeoff_0805.wav': '',
    'BGM_Game_Chasestars_120_4_4.wav': '',
    'BGM_Game_Collectstars_123_4_4.wav': '',
    'BGM_Game_Findstar_120_4_4.wav': '',
    'BGM_Game_GetPoints_125_4_4.wav': '',
    'BGM_Game_Timelimitarrival_136_4_4.wav': '',
    'BGM_BoxGame_PaperCrane_170_3_4.wav': '',
    'BGM_BoxGame_Pinball_180_2_4.wav': '',
    'BGM_Boxgame_RockPlant_NestingDoll_Intro_bpm120_m34.wav': '',
    'BGM_Boxgame_RockPlant_NestingDoll_Loop_bpm120_m34.wav': '',
    'BGM_Boxgame_RockPlant_NestingDoll_Lose_ChangeBPM_m34.wav': '',
    'BGM_Boxgame_RockPlant_NestingDoll_Victory_ChangeBPM_m34.wav': '',
    'BGM_Boxgame_RockPlant_NestingDoll_Win_ChangeBPM_m34.wav': '',
    'BGM_MiniGame_RockPlant_Dance_Lose_100_5_2.wav': '',
    'BGM_MiniGame_RockPlant_Dance_Main_100_5_2.wav': '',
    'BGM_MiniGame_RockPlant_Dance_Win_100_5_2.wav': '',
    'BGM_UI_MiniGames_DuckRun_Intro_80_4_4.wav': '',
    'BGM_UI_MiniGames_DuckRun_Loop_Normal_80_4_4.wav': '',
    'BGM_UI_MiniGames_DuckRun_Loop_Speedup_80_4_4.wav': '',
    'BGM_UI_MiniGames_DuckRun_Loop_Waiting_80_4_4.wav': '',
    'BGM_Mirror_Challenge1_Loop_89_4_4.wav': '',
    'BGM_Mirror_Challenge2_Intro_89_4_4.wav': '',
    'BGM_Mirror_Challenge2_Loop_89_4_4.wav': '',
    'Mirror_Challenge_DressTower_Opening.wav': '',
    'Mirror_Challenge_DressTower_Victory.wav': '',
    'BGM_Scene_Indoor_PuzzleSolvingRooom_Intro_Mastered_ChangeBPM.wav': '',
    'BGM_Scene_Indoor_PuzzleSolvingRooom_Loop_Mastered_ChangeBPM.wav': '',
    'Bgm_Scene_Shishutian_Train_01_bpm88_m44.wav': '',
    'Bgm_Scene_Shishutian_Train_02_bpm100_m44.wav': '',
    'BGM_Scene_Dongchashengtang_ChangeBPM.wav': '',
    'BGM_Scene_Indoor_InsightSanctuary_New_ChangeBPM.wav': '',
    'BGM_Scene_Lvye_WeddingPlace_60_4_4.wav': '',
    'BGM_Scene_Cave_GaintSnakeCave.wav': '',
    'BGM_Scene_Cave_QueenRelicCave.wav': '',
    'BGM_Scene_Cave_WishTownCaveGeneral.wav': '',
    'BGM_SceneYijiqu_ChangeBPM_Demo.wav': '',
    'BGM_Scene_GreenField_Caifengjidi_Night1_80_3_4.wav': '',
    'BGM_Scene_GreenField_Caifengjidi_Night2_ChangeBPM.wav': '',
    'BGM_Scene_GreenField_Huodongzhongxin_Day_Long_ChangeBPM.wav': '',
    'BGM_Scene_GreenField_Huodongzhongxin_Night_Long_ChangeBPM.wav': '',
    'BGM_Scene_GreenField_QueenRelicOutside_ChangeBPM.wav': '',
    'BGM_Scene_GreenField_Buchongxiaowu_Day.wav': '',
    'BGM_Scene_GreenField_Buchongxiaowu_Night.wav': '',
    'BGM_Scene_GreenField_FA_Day.wav': '',
    'BGM_Scene_GreenField_Port_Day.wav': '',
    'BGM_Scene_GreenField_Port_Night.wav': '',
    'BGM_Scene_Border_50_4_4.wav': '',
    'BGM_Scene_GreenField_QueenRelic_Day_1_78_3_4.wav.wav': '',
    'BGM_Scene_GreenField_QueenRelic_Day_1_Rain_78_3_4.wav': '',
    'BGM_Scene_GreenField_QueenRelic_Day_2_78_3_4.wav.wav': '',
    'BGM_Scene_GreenField_QueenRelic_Day_2_Rain_78_3_4.wav.wav': '',
    'BGM_Scene_GreenField_QueenRelic_Night_1_65_3_4.wav': '',
    'BGM_Scene_GreenField_QueenRelic_Night_1_Rain_65_3_4.wav': '',
    'BGM_Scene_GreenField_QueenRelic_Night_2_65_3_4.wav': '',
    'BGM_Scene_GreenField_QueenRelic_Night_2_Rain_65_3_4.wav': '',
    'BGM_Scene_RebelCamp_Day_1_BPM120_Rainy.wav': '',
    'BGM_Scene_RebelCamp_Day_2_BPM120.wav': '',
    'BGM_Scene_RebelCamp_Day_2_BPM120_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Day_01_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Day_02_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Day_03_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Day_04_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Day_05_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Day_06_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Day_07_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Day_08_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Day_09_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Day_10_Rainy_bpm50.wav': '',
    'BGM_Scene_Map01_Wild_Day_11_Rainy_bpm48.wav': '',
    'BGM_Scene_Map01_Wild_Day_12_Rainy_bpm56.wav': '',
    'BGM_Scene_Map01_Wild_Day_13_Rainy_bpm44.wav': '',
    'BGM_Scene_Map01_Wild_Day_01_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Day_02_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Day_03_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Day_04_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Day_05_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Day_06_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Day_07_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Day_08_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Day_09_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Day_10_Sunny_bpm50.wav': '',
    'BGM_Scene_Map01_Wild_Day_11_Sunny_bpm48.wav': '',
    'BGM_Scene_Map01_Wild_Day_12_Sunny_bpm56.wav': '',
    'BGM_Scene_Map01_Wild_Day_13_Sunny_bpm44.wav': '',
    'BGM_Scene_Map01_Wild_Night_01_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Night_02_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Night_03_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Night_04_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Night_05_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Night_06_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Night_07_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Night_08_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Night_09_Rainy.wav': '',
    'BGM_Scene_Map01_Wild_Night_10_Rainy_bpm76.wav': '',
    'BGM_Scene_Map01_Wild_Night_11_Rainy_bpm88.wav': '',
    'BGM_Scene_Map01_Wild_Night_12_Rainy_bpm62.wav': '',
    'BGM_Scene_Map01_Wild_Night_01_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Night_02_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Night_03_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Night_04_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Night_05_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Night_06_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Night_07_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Night_08_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Night_09_Sunny.wav': '',
    'BGM_Scene_Map01_Wild_Night_10_Sunny_bpm76.wav': '',
    'BGM_Scene_Map01_Wild_Night_11_Sunny_bpm88.wav': '',
    'BGM_Scene_Map01_Wild_Night_12_Sunny_bpm62.wav': '',
    'BGM_Scene_GreenField_General_Day_Long_1_81_4_4.wav': '',
    'BGM_Scene_GreenField_General_Day_Long_2_91_3_4.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_1.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_2.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_3.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_4.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_5.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_6.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_7.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_8.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_9.wav': '',
    'BGM_Scene_GreenField_General_Day_Long_1_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Day_Long_2_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_1_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_2_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_3_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_4_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_5_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_6_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_7_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_8_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Day_Short_9_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Night_Short_1_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Night_Short_2_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Night_Short_3_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Night_Short_4_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Night_Short_5_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Night_Short_6_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Night_Short_7_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Night_Short_8_Rainy.wav': '',
    'BGM_Scene_GreenField_General_Night_Short_9_Rainy.wav': '',
    'BGM_Scene_Map01_RuinsHill_Day_01_Rainy_bpm56_m34.wav': '',
    'BGM_Scene_Map01_RuinsHill_Day_02_Rainy_bpm60_m34.wav': '',
    'BGM_Scene_Map01_RuinsHill_Day_03_Rainy_bpm69_m34.wav': '',
    'BGM_Scene_Map01_RuinsHill_Day_01_Sunny_bpm56_m34.wav': '',
    'BGM_Scene_Map01_RuinsHill_Day_02_Sunny_bpm60_m34.wav': '',
    'BGM_Scene_Map01_RuinsHill_Day_03_Sunny_bpm69_m34.wav': '',
    'BGM_Scene_Map01_RuinsHill_Night_01_Rainy_bpm52_m34.wav': '',
    'BGM_Scene_Map01_RuinsHill_Night_02_Rainy_bpm44_m34.wav': '',
    'BGM_Scene_Map01_RuinsHill_Night_03_Rainy_bpm44_m34.wav': '',
    'BGM_Scene_Map01_RuinsHill_Night_01_Sunny_bpm52_m34.wav': '',
    'BGM_Scene_Map01_RuinsHill_Night_02_Sunny_bpm44_m34.wav': '',
    'BGM_Scene_Map01_RuinsHill_Night_03_Sunny_bpm44_m34.wav': '',
    'BGM_Scene_LegendAnimal_WhiteCow_Inside_Day_Clean_ChangeBPM.wav': '',
    'BGM_Scene_LegendAnimal_WhiteCow_Inside_Day_Crazy_Intro_ChangeBPM.wav': '',
    'BGM_Scene_LegendAnimal_WhiteCow_Inside_Day_Crazy_Loop_105_4_4.wav': '',
    'BGM_Scene_LegendAnimal_WhiteCow_Inside_Night_Loop_95_4_4.wav': '',
    'BGM_Scene_LegendAnimal_WhiteCow_Outside_ChangeBPM.wav': '',
    'BGM_Scene_LegendAnimal_Swan_1.wav': '',
    'BGM_Scene_LegendAnimal_Swan_2.wav': '',
    'BGM_Scene_LegendAnimal_Swan_3.wav': '',
    'BGM_Scene_LegendAnimal_Swan_4.wav': '',
    'BGM_Scene_Challenge_AdvancedTable_New_ChangeBPM.wav': '',
    'BGM_Scene_Indoor_Chenxilvguan_125_3_4_MixV1.wav': '',
    'BGM_Scene_Indoor_Dapeishixiehui_120_3_4_MixV1.wav': '',
    'BGM_Scene_Indoor_Guangyufeiniaocanting_Day_130_ChangeBPM_4_4_MixV1.wav': '',
    'BGM_Scene_Indoor_Guangyufeiniaocanting_Night_104_4_4.wav': '',
    'BGM_Scene_Indoor_InfinityMirror_ChangeBPM.wav': '',
    'BGM_Scene_Indoor_Marksclothingshop_Day_108_3_4_MixV1.wav': '',
    'BGM_Scene_Indoor_Marksclothingshop_Night_60_4_4.wav': '',
    'BGM_Scene_Indoor_Minju_Day_102_3_4_Update.wav': '',
    'BGM_Scene_Indoor_Minju_Night_64_4_4_Update.wav': '',
    'BGM_Scene_Indoor_Nuonuoyizhijia_70_4_4.wav': '',
    'BGM_Scene_Indoor_LimaoClub.wav': '',
    'BGM_Scene_Indoor_LimaoClub_Reverb.wav': '',
    'BGM_Scene_WishTown_Backmountain_Day_A1.wav': '',
    'BGM_Scene_WishTown_Backmountain_Day_A2.wav': '',
    'BGM_Scene_WishTown_Backmountain_Night_A1.wav': '',
    'BGM_Scene_WishTown_Backmountain_Night_A2.wav': '',
    'BGM_Scene_WishTown_East_Day_A1.wav': '',
    'BGM_Scene_WishTown_East_Day_A2.wav': '',
    'BGM_Scene_WishTown_East_Night_A1.wav': '',
    'BGM_Scene_WishTown_East_Night_A2.wav': '',
    'BGM_Scene_WishTown_Lakeside_Day_A1.wav': '',
    'BGM_Scene_WishTown_Lakeside_Day_A2.wav': '',
    'BGM_Scene_WishTown_Lakeside_Night_A1.wav': '',
    'BGM_Scene_WishTown_Lakeside_Night_A2.wav': '',
    'BGM_Scene_WishTown_West_Day_A1.wav': '',
    'BGM_Scene_WishTown_West_Day_A2.wav': '',
    'BGM_Scene_WishTown_West_Day_B1.wav': '',
    'BGM_Scene_WishTown_West_Day_B2.wav': '',
    'BGM_Scene_WishTown_West_Night_A1.wav': '',
    'BGM_Scene_WishTown_West_Night_A2.wav': '',
    'BGM_Scene_WishTown_Backmountain_Day_A1_Rainy.wav': '',
    'BGM_Scene_WishTown_Backmountain_Day_A2_Rainy.wav': '',
    'BGM_Scene_WishTown_Backmountain_Night_A1_Rainy.wav': '',
    'BGM_Scene_WishTown_Backmountain_Night_A2_Rainy.wav': '',
    'BGM_Scene_WishTown_East_Day_A1_Rainy.wav': '',
    'BGM_Scene_WishTown_East_Day_A2_Rainy.wav': '',
    'BGM_Scene_WishTown_East_Night_A1_Rainy.wav': '',
    'BGM_Scene_WishTown_East_Night_A2_Rainy.wav': '',
    'BGM_Scene_WishTown_Lakeside_Day_A1_Rainy.wav': '',
    'BGM_Scene_WishTown_Lakeside_Day_A2_Rainy.wav': '',
    'BGM_Scene_WishTown_Lakeside_Night_A1_Rainy.wav': '',
    'BGM_Scene_WishTown_Lakeside_Night_A2_Rainy.wav': '',
    'BGM_Scene_WishTown_West_Bright_Rainy_part1.wav': '',
    'BGM_Scene_WishTown_West_Bright_Rainy_part2.wav': '',
    'BGM_Scene_WishTown_West_Day_Rainy_part1.wav': '',
    'BGM_Scene_WishTown_West_Day_Rainy_part2_v2.wav': '',
    'BGM_Scene_WishTown_West_Night_Rainy_part1.wav': '',
    'BGM_Scene_WishTown_West_Night_Rainy_part2.wav': '',
    'BGM_Scene_Yewai_New_Night_1.wav': '',
    'BGM_Scene_Yewai_New_Night_2.wav': '',
    'BGM_Scene_Yewai_New_Night_3.wav': '',
    'BGM_Scene_Yewai_New_Night_4.wav': '',
    'BGM_Scene_Yewai_New_Night_5.wav': '',
    'BGM_Scene_Yewai_New_Night_6.wav': '',
    'BGM_Scene_Yewai_New_Night_7.wav': '',
    'BGM_Scene_Yewai_New_Night_8.wav': '',
    'BGM_Scene_Yewai_New_Night_9.wav': '',
    'BGM_Scene_Qiyuanshulin_WishgodSong_Extra.wav': '愿望神之歌 | 加长',
    'BirdWhistle_Clarinet_1.wav': '',
    'BirdWhistle_Clarinet_2.wav': '',
    'BirdWhistle_Clarinet_3.wav': '',
    'BirdWhistle_Clarinet_4.wav': '',
    'BirdWhistle_Clarinet_5.wav': '',
    'BirdWhistle_Clarinet_6.wav': '',
    'BirdWhistle_Clarinet_7.wav': '',
    'Npc_Guitar_Caifengjidi_Version2.wav': '',
    'Npc_Lute_Version2.wav': '',
    'Npc_Guitar_Lonely_DryMono.wav': '',
    'Npc_Guitar_Play_DryMono.wav': '',
    'Npc_Piano_162_3_4_Dry.wav': '',
    'KingParrot_Sing1.wav': '',
    'KingParrot_Sing2.wav': '',
    'KingParrot_Sing3.wav': '',
    'KingParrot_Sing4.wav': '',
    'KingParrot_Sing5.wav': '',
    'BGM_LS_BattlePass_Performance.wav': '',
    'BGM_Animation_Qiyuanshulin_LS0100_SC303.wav': '过场动画303',
    'BGM_Animation_Qiyuanshulin_LS0100_SC305.wav': '过场动画305',
    'BGM_Animation_Qiyuanshulin_LS0100_SC306.wav': '过场动画306',
    'Bgm_Animation_Qiyuanshulin_LS0100_SC307.wav': '过场动画307',
    'BGM_Animation_Qiyuanshulin_LS0100_SC308.wav': '过场动画308',
    'BGM_Animation_Qiyuanshulin_LS0100_SC309.wav': '过场动画309',
    'BGM_Animation_Qiyuanshulin_LS0100_SC311.wav': '过场动画311',
    'BGM_Animation_Qiyuanshulin_LS0100_SC313_Master.wav': '过场动画313',
    'BGM_Animation_Qiyuanshulin_LS0100_SC315.wav': '过场动画315',
    'BGM_Animation_Qiyuanshulin_LS0100_SC316.wav': '过场动画316',
    'Bgm_Animation_Qiyuanshulin_LS0100_SC317.wav': '过场动画317',
    'Bgm_Animation_Qiyuanshulin_LS0100_SC318.wav': '过场动画318',
    'BGM_Boss_Qigda_P1_OpenLS_136_4_4.wav': '奇格格达Boss战 | 开场',
    'BGM_Boss_Qigda_P2_EndingLS_136_4_4.wav': '奇格格达Boss战 | 收场',
    'BGM_Dialogue_E01_Easy_104_3_4.wav': '',
    'BGM_Dialogue_E02.1_Daily_112_4_4.wav': '',
    'BGM_Dialogue_E02.2_Daily_88_4_4.wav': '',
    'BGM_Dialogue_E02_Daily_74_4_4.wav': '',
    'BGM_Dialogue_E03.1_Funny_114_4_4.wav': '',
    'BGM_Dialogue_E03_Funny_96_4_4to3_4.wav': '',
    'BGM_Dialogue_E04_Tension_120_3_4.wav': '',
    'BGM_Dialogue_E05.1_Suspenseful_80_4_4.wav': '',
    'BGM_Dialogue_E05_Suspenseful_80_3_4.wav': '',
    'BGM_Dialogue_E08_Tense_96_4_4.wav': '',
    'BGM_Dialogue_E10.2_Warm_102_4_4.wav': '',
    'BGM_Dialogue_E10_Warm_122_3_4.wav': '',
    'BGM_Dialogue_E10_Warm_Exclusive.wav': '',
    'BGM_Dialogue_E11_Sad_98_4_4.wav': '',
    'BGM_Dialogue_Violin_01.wav': '',
    'BGM_Dialogue_Violin_Ballade_of_Homeland_Fragment1_3.wav': '',
    'BGM_Dialogue_Violin_Ballade_of_Homeland_FullwPno.wav': '',
    'BGM_Dialogue_Violin_Shishutian.wav': '',
    'BGM_Plot_1_1_Room3_Intro_102_3_4_OutsideBegin_MixV1.wav': '',
    'BGM_Plot_1_1_Room3_Loop_124_3_4_MixV1.wav': '',
    'BGM_Plot_1_1_Room4_72_4_4_BlueDragonPark_MixV1.wav': '',
    'BGM_Plot_1_3_Room3_115_3_4.wav': '',
    'BGM_Plot_1_3_Room4_1_110_4_4.wav': '',
    'BGM_Plot_1_3_Room5_Intro_205_4_4.wav': '',
    'BGM_Plot_1_3_Room5_Loop_205_4_4.wav': '',
    'BGM_Plot_1_3_Room5_Outro_205_4_4.wav': '',
    'Plot_1_3_Dark_70_3_4.wav': '',
    'Plot_1_3_Room1&2_160_3_4.wav': '',
    'Plot_1_3_Room4_2_V4_110_4_4.wav': '',
    'BGM_Plot_1_5_Room1_72_4_4_RecMix_V1.wav': '',
    'BGM_Plot_1_5_Room2_72_4_4_RecMix_V1.wav': '',
    'BGM_Plot_1_5_Room4_Folded_Final1.wav': '',
    'BGM_Plot_1_5_Room5Final_72_4_4.wav': '',
    'Folded_FX.wav': '',
    'Folded_MMA_Cut.wav': '',
    'BGM_Plot_1_5_Room3_Intro_72_4_4.wav': '',
    'BGM_Plot_1_5_Room3_Loop_72_4_4.wav': '',
    'BGM_Plot_1_5_Room4Entrance_Intro_69_4_4.wav': '',
    'BGM_Plot_1_5_Room4Entrance_Loop_69_4_4.wav.wav': '',
    'BGM_Plot_1_5_Room5_72_4_4.wav': '',
    'Plot1_5Room4_FlyC_Loop_78_4_4_v2.wav': '',
    'BGM_Plot_2_1_Qianting_Music_NewMidi_80_4_4.wav': '',
    'BGM_Plot_2_1_Room6_Wangzuo_Changemarker_230703.wav': '',
    'Plot_2_1_GhostVoice_2.wav': '',
    'Plot_2_1_Room1&2_ChangeBPM.wav': '',
    'Plot_2_1_Room3_100_3_4.wav': '',
    'Plot_2_1_Room4_Intro_Music_130_3_4.wav': '',
    'Plot_2_1_Room4_Loop_Music_130_3_4.wav': '',
    'Plot_2_1_Room4_Loop_SVVocal_130_3_4.wav': '',
    'Plot_2_1_Room4_Loop_SVVocal_Reverb_130_3_4.wav': '',
    'Plot_2_1_Room5_132_4_4.wav': '',
    'Plot_2_1_Room6_Qianting_Vocal_80_4_4.wav': '',
    'Plot_2_1_Room6_Qianting_Vocal_Reverb_80_4_4.wav': '',
    'BGM_Plot_2_2_Room1_Quiet_144_3_4.wav': '',
    'BGM_Plot_2_2_Room2_2_160_3_4_Comp.wav': '',
    'BGM_Plot_2_2_Room3_Intro_LS_170_3_4.wav': '',
    'BGM_Plot_2_2_Room3_Oneshot_170_3_4_Comp.wav': '',
    'BGM_Plot_2_2_Room4_Entrance_ChangeBPM_Comp.wav': '',
    'BGM_Plot_2_2_Room4_Loop_Comp.wav': '',
    'BGM_Plot_2_2_Room5_Full_92_3_4_Comp.wav': '',
    'Plot2_2Room2_1Entrance_92_4_4.wav': '',
    'Plot2_2Room2_1_Loop_160_3_4.wav': '',
    'Plot2_2Room2_1_LS_160_2_4.wav': '',
    'Plot2_2_Room1_144_3_4.wav': '',
    'BGM_Plot_3_1_Room1_IntroRoom_110_3_4.wav': '',
    'BGM_Plot_3_1_Room2_Transporter_v2_146_3_4.wav': '',
    'BGM_Plot_3_1_Room3_Transporter_TensionVersion_146_3_4.wav.wav': '',
    'BGM_Plot_3_1_Room4_Waterfalls_Long_ChangeBPM.wav.wav': '',
    'BGM_Plot_3_1_Room5_Pontoon_100_3_4.wav': '',
    'BGM_Plot_3_1_Room6_Office_110_3_4.wav': '',
    'BGM_Plot_3_1_Room7_Battle_146_4_4.wav': '',
    'Bgm3_2_Room5Entrance_140_4_4.wav': '',
    'Bgm_Animation_3_2_LS0100_SC223.wav': '',
    'Bgm_Animation_3_2_LS_0100_SC217.wav': '',
    'Bgm_Animation_3_2_LS_0100_SC219.wav': '',
    'Plot3_2_Room1_Intro_80_3_4.wav': '',
    'Plot3_2_Room1_Loop_80_3_4.wav': '',
    'Plot3_2_Room2_Intro_ChangeBPM.wav': '',
    'Plot3_2_Room2_Loop_130_4_4.wav': '',
    'Plot3_2_Room3_Loop_130_4_4.wav': '',
    'Plot3_2_Room4_Intro_80_6_8.wav': '',
    'Plot3_2_Room4_Loop_80_6_8.wav': '',
    'Plot3_2_Room5_Intro_150_4_4.wav': '',
    'Plot3_2_Room5_Loop_NewDrums_150_4_4.wav': '',
    'BGM_Animation_4_1_LS_0100_SC304.wav': '过场动画304',
    'BGM_Plot_4_1_Room1Intro_ChangeBPM.wav': '副本·缇米丝的美妆工坊 | 房间1 | 开场',
    'BGM_Plot_4_1_Room1Loop_82_4_4.wav': '副本·缇米丝的美妆工坊 | 房间1 | 循环',
    'BGM_Plot_4_1_Room1Loop_TrackCombine_Transmit_Reverse_82_4 _4.wav': '副本·缇米丝的美妆工坊 | 房间1 | 循环 | 反向',
    'BGM_Plot_4_1_Room2Intro_ChangeBPM.wav': '副本·缇米丝的美妆工坊 | 房间2 | 开场',
    'BGM_Plot_4_1_Room2Loop_105_4_4.wav': '副本·缇米丝的美妆工坊 | 房间2 | 循环',
    'BGM_Plot_4_1_Room3Loop_100_4_4.wav': '副本·缇米丝的美妆工坊 | 房间3 | 循环',
    'BGM_Plot_4_1_Room3Loop_Transmit_ForwadDirection_100_4_4.wav': '副本·缇米丝的美妆工坊 | 房间3 | 循环 | 正向',
    'BGM_Plot_4_1_Room3Loop_Transmit_Reverse_100_4_4.wav': '副本·缇米丝的美妆工坊 | 房间3 | 循环 | 反向',
    'BGM_Plot_4_1_Room5Intro_100_4_4.wav': '副本·缇米丝的美妆工坊 | 房间5 | 开场',
    'BGM_Plot_4_1_Room5Loop_100_4_4.wav': '副本·缇米丝的美妆工坊 | 房间5 | 循环',
    'BGM_Plot_4_2_Room0_100_4_4.wav': '副本·古铸剑遗址 | 房间0',
    'BGM_Plot_4_2_Room1_100_4_4.wav': '副本·古铸剑遗址 | 房间1',
    'BGM_Plot_4_2_Room1_Silence_100_4_4.wav': '副本·古铸剑遗址 | 房间1 | 安静',
    'BGM_Plot_4_2_Room2_114_4_4.wav': '副本·古铸剑遗址 | 房间2',
    'BGM_Plot_4_2_Room3_100_4_4.wav': '副本·古铸剑遗址 | 房间3',
    'BGM_Plot_4_2_Room4_P1_Silence_154_3_4.wav': '副本·古铸剑遗址 | 房间4 | P1 | 安静',
    'BGM_Plot_4_2_Room4_P2_NoChoir_154_3_4.wav': '副本·古铸剑遗址 | 房间4 | P2 | 无合唱',
    'BGM_Plot_4_2_Room4_P3_Choir_154_3_4.wav': '副本·古铸剑遗址 | 房间4 | P3 | 合唱',
    'BGM_Plot_4_2_Room5_136_4_4.wav': '副本·古铸剑遗址 | 房间5',
    'BGM_Plot_4_2_Room5_Battle_82_4_4.wav': '副本·古铸剑遗址 | 房间5 | 战斗',
    'BGM_Plot_Prologue_1_HeavenPark_Demo_Loop_Cut2_BPM132.wav': '',
    'BGM_Plot_Prologue_1_HeavenPark_Loop.wav': '',
    'BGM_Plot_Prologue_1_HeavenPark_OneShot.wav': '',
    'BGM_Plot_Prologue_2_Ruins_Intro.wav': '',
    'BGM_Plot_Prologue_2_Ruins_Loop.wav': '',
    'BGM_Plot_Prologue_3_StarterArea_Intro.wav': '',
    'BGM_Plot_Prologue_3_StarterArea_Loop.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_AncientVillage_Normal_Day_01_Sunny_bpm92_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_AncientVillage_Normal_Day_02_Sunny_bpm83_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_AncientVillage_Normal_Night_01_Sunny_bpm84_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_AncientVillage_Normal_Night_02_Sunny_bpm80_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_AncientVillage_Storyline_Day_Sunny_bpm92_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_AncientVillage_Storyline_Night_Sunny_bpm83_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_FarmRockTree_Day_01_Sunny_bpm100_m34.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_FarmRockTree_Day_02_Sunny_bpm125_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_FarmRockTree_Night_01_Sunny_bpm120_m34.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_FarmRockTree_Night_02_Sunny_bpm95_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_Glide_Day_01_Sunny_bpm126_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_Glide_Day_02_Sunny_bpm145_m34.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_HootingStation_Normal_Day_01_Sunny_bpm100_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_HootingStation_Normal_Day_02_bpm130_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_HootingStation_Normal_Night _01_bpm90_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_HootingStation_Normal_Night _02_Sunny_bpm120_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_HootingStation_Stoyline_Day_01_bpm80_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_HootingStation_Stoyline_Night_01_bpm70_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_JoyfulMarket_Normal_Day_01_bpm88_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_JoyfulMarket_Normal_Day_02_Sunny_bpm62_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_JoyfulMarket_Normal_Night_01_bpm88_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_JoyfulMarket_Normal_Night_02_bpm62_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_JoyfulMarket_StoryLine_Day_01_bpm120_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_JoyfulMarket_StoryLine_Night_01_bpm108_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_RippleManor_Day_01_Sunny_bpm70_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_RippleManor_Day_02_Sunny_bpm70_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_RippleManor_Night_01_Sunny_bpm55_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_RippleManor_Night_02_Sunny_bpm58_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_RockCrown_Normal_Day_01_bpm86_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_RockCrown_Normal_Day_02_bpm71_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_RockCrown_Normal_Night_01_bpm82_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_RockCrown_Normal_Night_02_bpm62_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_RockCrown_Storyline_Day_01_bpm102_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_RockCrown_Storyline_Night_01_Sunny_bpm95_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_WaterspoutGlide_Day_01_Sunny_bpm126_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_WaterspoutGlide_Day_02_Sunny_bpm115_m44.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_Wild_Luoshishan_Day_01_sunny_bpm72_m68.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_Wild_Luoshishan_Night_01_Sunny_bpm60_m68.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_Windmill_Day_01_Sunny_bpm110_m34.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_Windmill_Day_02_Sunny_bpm110_m34.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_Windmill_Night_01_Sunny_bpm100_m34.wav': '',
    'BGM_Scene_ShiShuTian_Unpopulated_Windmill_Normal_Night_02_bpm60_m44.wav': '',
    'BGM_Scene_ShiShuTian_Village_HuatianCunzhuang_Day_100_4_4_Loop.wav': '',
    'BGM_Scene_ShiShuTian_Village_HuatianCunzhuang_Day_To_Night.wav': '',
    'BGM_Scene_ShiShuTian_Village_HuatianCunzhuang_Night_90_3_4_Loop.wav': '',
    'BGM_Scene_ShiShuTian_Village_HuatianCunzhuang_Night_To_Day.wav': '',
    'BGM_Scene_ShiShuTian_Village_Market_Day_bpm67_m44.wav': '',
    'BGM_Scene_ShiShuTian_Village_Market_Night_noGTR_bpm67_m44.wav': '',
    'BGM_Scene_ShiShuTian_Village_Weaving_WorkShop_Day_01_Sunny_98_m128.wav': '',
    'BGM_Scene_ShiShuTian_Village_Weaving_Workshop_Night_01_Sunny_62_m68.wav': '',
    'BGM_Scene_ShiShuTian_Wild_JuMinQu_Day_01_sunny_72_6_8.wav': '',
    'BGM_Scene_ShiShuTian_Wild_JuMinQu_Night_01_sunny_60_6_8.wav': '',
    'BGM_Scene_Qiyuanshulin_BadWishesHill_Day_01_Sunny_bpm90_ChangeTimeSignature.wav': '怪味愿望山坡 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_BadWishesHill_Day_02_Sunny_bpm100_m44.wav': '怪味愿望山坡 | 白天 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_BadWishesHill_Night_01_Sunny_bpm53_m44.wav': '怪味愿望山坡 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_BadWishesHill_Night_02_Sunny_bpm100_m44.wav': '怪味愿望山坡 | 夜晚 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_CelebrationCenter_Night_01_Vox_Sunny_bpm63_m44.wav': '心愿庆典管理处 | 夜晚 | 01 | 有人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_CelebrationCenter_Night_02_Vox_Sunny_bpm62_m44.wav': '心愿庆典管理处 | 夜晚 | 02 | 有人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_ChigdaCavePrison.wav': '监禁洞窟',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Night_01_noVox_Sunny_bpm63_m44.wav': '金蔷薇花谷 | 夜晚 | 01 | 无人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Night_02_noVox_Sunny_bpm62_m44.wav': '金蔷薇花谷 | 夜晚 | 02 | 无人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Normal_Day_01_noVox_Sunny_bpm75_m68.wav': '金蔷薇花谷 | 白天 | 01 | 无人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Normal_Day_01_Sunny_bpm75_m68.wav': '金蔷薇花谷 | 白天 | 01 | 有人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Normal_Day_02_noVox_Sunny_bpm87_m44.wav': '金蔷薇花谷 | 白天 | 02 | 无人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Normal_Day_02_Sunny_bpm87_m44.wav': '金蔷薇花谷 | 白天 | 02 | 有人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Storyline_Day_01_Sunny_bpm80_m44.wav': '金蔷薇花谷 | 剧情 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_GuardsGarrison_Day_01_Sunny_bpm102_m44.wav': '千愿巨树·近卫队驻地 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_GuardsGarrison_Day_02_Sunny_bpm86_m44.wav': '千愿巨树·近卫队驻地 | 白天 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_GuardsGarrison_Night_01_Sunny_bpm68_m44.wav': '千愿巨树·近卫队驻地 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_GuardsGarrison_Night_02_bpm86_m44.wav': '千愿巨树·近卫队驻地 | 夜晚 | 02',
    'BGM_Scene_Qiyuanshulin_GT_Living_Day_01_Sunny_bpm102_m44.wav': '千愿巨树·居民区 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Living_Day_02_Sunny_bpm86_m44.wav': '千愿巨树·居民区 | 白天 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Living_Gtr_Night_01_Sunny_bpm68_m44_v2.wav': '千愿巨树·居民区 | 夜晚 | 01 | 有吉他 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Living_Night_02_bpm86_m44.wav': '千愿巨树·居民区 | 夜晚 | 02',
    'BGM_Scene_Qiyuanshulin_GT_Living_Vox_Night_01_Sunny_bpm68_m44_v2.wav': '千愿巨树·居民区 | 夜晚 | 01 | 有人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_River_Night_01_Sunny_bpm68_m44.wav': '千愿巨树·巨树浅滩 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Normal_Day_02_Sunny_bpm86_m44.wav': '千愿巨树·心愿圣殿 | 白天 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Normal_Night_01_bpm68_m44.wav': '千愿巨树·心愿圣殿 | 夜晚 | 01',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Normal_Night_02_bpm86_m44.wav': '千愿巨树·心愿圣殿 | 夜晚 | 02',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Storyline_Day_01_Sunny_bpm102_m44_v2.wav': '千愿巨树·心愿圣殿 | 剧情 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Storyline_Day_02_bpm86_m44.wav': '千愿巨树·心愿圣殿 | 剧情 | 白天 | 02',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Storyline_Day_Sunny_bpm102_m44.wav': '千愿巨树·心愿圣殿 | 剧情 | 白天 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Storyline_Night_01_bpm68_m44.wav': '千愿巨树·心愿圣殿 | 剧情 | 夜晚 | 01',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Storyline_Night_02_bpm86_m44.wav': '千愿巨树·心愿圣殿 | 剧情 | 夜晚 | 02',
    'BGM_Scene_Qiyuanshulin_QCCenter_Day_01_Sunny_bpm134_m34.wav': '愿望质检中心 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_QCnRND_Night_01_Sunny_bpm100_m34.wav': '愿望质检中心&心愿研发所 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_RiverCanyon_Day_01_bpm112_m44.wav': '古木河畔 | 白天 | 01',
    'BGM_Scene_Qiyuanshulin_RiverCanyon_Night_01_Sunny_bpm86_m44.wav': '古木河畔 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_River_Day_01_bpm102_m44.wav': '河畔 | 白天 | 01',
    'BGM_Scene_Qiyuanshulin_River_Day_02_bpm86_m44.wav': '河畔 | 白天 | 02',
    'BGM_Scene_Qiyuanshulin_River_Night_02_bpm86_m44.wav': '河畔 | 夜晚 | 02',
    'BGM_Scene_Qiyuanshulin_RNDInstitute_Day_01_Sunny_bpm134_m34.wav': '心愿研发所 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_SwordFoundry_Day_01_Sunny_bpm120_m44.wav': '古铸剑遗址 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_SwordFoundry_Day_02_Sunny_bpm120_m44.wav': '古铸剑遗址 | 白天 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_SwordFoundry_Night_01_Sunny_bpm120_m44.wav': '古铸剑遗址 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_SwordFoundry_Night_02_Sunny_bpm120_m44.wav': '古铸剑遗址 | 夜晚 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_TimisBeautyFactory_Day_01_bpm124_m14.wav': '缇米丝的美妆工坊 | 白天 | 01',
    'BGM_Scene_Qiyuanshulin_TimisBeautyFactory_Night_01_bpm124_m44.wav': '缇米丝的美妆工坊 | 夜晚 | 01',
    'BGM_Scene_Qiyuanshulin_VanishingStarland_Day_01_Sunny_bpm94_m34.wav': '星没之地 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_VanishingStarland_Night_01_Sunny_bpm85_m34.wav': '星没之地 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_VisaCave_bpm65_m44.wav': '心愿通行许可处 | 洞窟内',
    'BGM_QiYuanShuLin_LegendAnimal_CharmingFox_Clean.wav': '传奇生灵·曦光狐 | 已清洁',
    'BGM_QiYuanShuLin_LegendAnimal_CharmingFox_Dirty.wav': '传奇生灵·曦光狐 | 未清洁',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Indoor_Sunny_bpm57_m44.wav': '千愿巨树·心愿圣殿 | 室内 | 晴天',
    'BGM_Scene_Qiyuanshulin_QCCenter_Indoor_bpm130_m34.wav': '愿望质检中心 | 室内',
    'BGM_Scene_Housing_Indoor_01_bpm72_m44.wav': '',
    'BGM_Scene_Housing_LivingArea_Day_01_Sunny_bpm100_m44.wav': '',
    'BGM_Scene_Housing_LivingArea_Night_01_Sunny_bpm75_m44.wav': '',
    'BGM_Scene_Housing_PlayingArea_Day_01_Sunny_bpm100_m44.wav': '',
    'BGM_Scene_Housing_PlayingArea_Night_01_Sunny_bpm75_m44.wav': '',
    'BGM_scene_rainbow_01_day_bpm115_3_4 V5.wav': '',
    'BGM_scene_map01_HuoBanJie_day_01_bpm115_4_4.wav': '',
    'BGM_Scene_Map01_HuoBanJie_Night_118BPM.wav': '',
    'SingingBlueDragon_HarpShow_.wav': '',
    'SingingBlueDragon_Short_1.wav': '',
    'SingingBlueDragon_Short_2.wav': '',
    'SingingBlueDragon_Short_3.wav': '',
    'SingingBlueDragon_Short_4.wav': '',
    'Bgm_CoolGuy_FittingRoom.wav': '',
    'BGM_UI_Infinityheart_New_ChangeBPM.wav': '',
    'BGM_UI_Login_96_3_4_MixV1.wav': '',
    'Mirror_Challenge_UI.wav': '',
    'TogetherTillInfinity_InProg7L2.Mstr.24.wav': '',
    'BGM_UI_Login_CBT2_BinkVideo.wav': '',
    'BGM_Boxgame_QiYuanShuLin_Wishball_Intro_ChangeBPM.wav': '',
    'BGM_Boxgame_QiYuanShuLin_Wishball_Lose_bpm110_m44.wav': '',
    'BGM_Boxgame_QiYuanShuLin_Wishball_Place_bpm110_m44.wav': '游戏·愿望球速达 | 放置阶段',
    'BGM_Boxgame_QiYuanShuLin_Wishball_Transport_bpm110_m44.wav': '游戏·愿望球速达 | 运输阶段',
    'BGM_Boxgame_QiYuanShuLin_Wishball_Win_bpm110_m44.wav': '',
    'BGM_Scene_ShiShuTian_Village_Market_Night_OnlyGTR_bpm67_m44.wav': '',

}