

CURRENT_ALBUM = "花愿镇.png"

ASS_VIDEO_GENERATOR_PATH = 'E:\\AssVideoGenerator'

GENERATE_VIDEO_PATHS1 = [
    "output/audio1/main/WishTown2023/Indoor",
    "output/audio1/ui_outgame",
]

GENERATE_VIDEO_PATHS = [
    "output/audio1/Animation/Mirror_Challenge",
    "output/audio1/Animation/function",
    "output/audio1/Animation/SingingDragon_QiYuanShuLin",
    "output/audio1/Combat/General_Combat_V1_Lvye",
    "output/audio1/Event",
    "output/audio1/SingingBlueDragon",
    "output/audio1/ui_outgame",
    "output/audio1/Online",
    "output/audio1/main",
    "output/audio1/PLOT"
]

FILE_MAP = {
    'Silence Wav.wav': '',
    'BGM_LS_ClothingEvolution_Butterfly_ChangeBPM.wav': '服装进化 | 蝶屿风袭',
    'BGM_LS_ClothingEvolution_General_1.wav': '服装进化 | 一般1',
    'BGM_LS_ClothingEvolution_General_2.wav': '服装进化 | 一般2',
    'BGM_LS_ClothingEvolution_S0062_Goldenrose.wav': '服装进化 | 心愿金蔷薇',
    'BGM_LS_ClothingEvolution_S0128_SilverNightingale.wav': '服装进化 | 咏叹银夜莺',
    'BGM_LS_ClothingEvolution_S0145_SeaSpray_Dress.wav': '服装进化 | 谕浪希声',
    'BGM_LS_ClothingEvolution_S0161_DreamElf.wav': '服装进化 | 花漾梦萦',
    'BGM_LS_ClothingEvolution_S0165_Jingying.wav': '服装进化 | 晶莹诗集',
    'BGM_LS_ClothingEvolution_SpringFlower_v2.wav': '服装进化 | SpringFlower | V2',
    'BGM_LS_ClothingEvolution_SwanLake_3.wav': '服装进化 | 天鹅童话',
    'General_Fresh.wav': '服装进化 | 一般焕新',
    'Bgm_CoolSovereign_Appear.wav': '帅气天王 | 出现',
    'Bgm_CoolSovereign_Battle.wav': '帅气天王 | 比拼',
    'Bgm_CoolSovereign_Battle_Fail.wav': '帅气天王 | 失败',
    'Bgm_CoolSovereign_Battle_Success.wav': '帅气天王 | 成功',
    'LS0100_SC123_ChangeBPM_0708.wav': '过场动画123 | 典雅天王 | 过渡用',
    'LS0100_SC126_ChangeBPM_0628.wav': '过场动画126 | 典雅天王 | 过渡用',
    'LS0100_SC127_ChangeBPM_0628.wav': '过场动画127 | 典雅天王 | 过渡用',
    'LS0100_SC128_ChangeBPM_0628.wav': '过场动画128 | 典雅天王 | 过渡用',
    'LS0100_SC129_ChangeBPM.wav': '过场动画129 | 典雅天王 | 过渡用',
    'LS0100_SC121_BGM.wav': '过场动画121 | 典雅天王',
    'Bgm_FreshSoveign_Success.wav': '清新天王 | 获胜',
    'Bgm_FreshSovereign_Battle_Fail.wav': '清新天王 | 失败',
    'Bgm_FreshSovereign_Battle_Perfect.wav': '清新天王 | 完美',
    'Bgm_FreshSovereign_Battle_v1.wav': '清新天王 | V1',
    'BGM_ui_summon_loop_bpm208_m34.wav': '共鸣 | 循环',
    'BGM_ui_summon_lucky_intro_bpm208_m34.wav': '共鸣 | 出金 | 开场',
    'BGM_ui_summon_normal_intro_bpm208_m34.wav': '共鸣 | 一般 | 开场',
    'LS_Resonance_Performance.wav': '共鸣 | 演出',
    'BGM_Animation_ShiShuTian_GhostTrainFirstTime.wav': '过场动画 | 首次登上幽灵列车',
    'BGM_Animation_ShiShuTian_LS0100_SC201.wav': '过场动画201',
    'BGM_Animation_ShiShuTian_LS0100_SC202.wav': '过场动画202',
    'BGM_Animation_ShiShuTian_LS0100_SC203.wav': '过场动画203',
    'BGM_Animation_ShiShuTian_LS0100_SC204.wav': '过场动画204',
    'BGM_Animation_ShiShuTian_LS0100_SC205.wav': '过场动画205',
    'BGM_Animation_ShiShuTian_LS0100_SC206.wav': '过场动画206',
    'BGM_Animation_ShiShuTian_LS0100_SC207.wav': '过场动画207',
    'BGM_Animation_ShiShuTian_LS0100_SC211.wav': '过场动画211',
    'BGM_Animation_ShiShuTian_LS0100_SC213.wav': '过场动画213',
    'BGM_Animation_ShiShuTian_LS0100_SC214.wav': '过场动画214',
    'BGM_Animation_ShiShuTian_LS0100_SC215.wav': '过场动画215',
    'BGM_Animation_ShiShuTian_LS0100_SC220C_Master_Intro_146_4_4.wav': '过场动画220C | 开场',
    'BGM_Animation_ShiShuTian_LS0100_SC220C_Master_Loop_146_4_4.wav': '过场动画220C | 循环',
    'BGM_Animation_ShiShuTian_LS0100_SC220D_Master_Oneshot_146_4_4.wav': '过场动画220D | 单次',
    'BGM_Animation_ShiShuTian_LS0100_SC220E_Master_Oneshot.wav': '过场动画220E | 单次',
    'BGM_Animation_ShiShuTian_LS0100_SC220_Master_Intro_146_4_4.wav': '过场动画220 | 开场',
    'BGM_Animation_ShiShuTian_LS0100_SC220_Master_Loop_146_4_4.wav': '过场动画220 | 循环',
    'BGM_Animation_ShiShuTian_LS0100_SC222.wav': '过场动画222',
    'BGM_Animation_ShiShuTian_LS_ShowGlideRoute.wav': '过场动画 | 开启空中通路',
    'BGM_Animation_ShiShuTian_LS_TreeHeartWater_01.wav': '过场动画 | 石树之心 | 石露花浆',
    'BGM_Animation_ShiShuTian_LS_TreeHeart_01.wav': '过场动画 | 石树之心',
    'Mirror_Challenge_Battle.wav': '奇迹之冠 | 比拼',
    'Mirror_Challenge_Battle_Fail.wav': '奇迹之冠 | 失败',
    'Mirror_Challenge_Battle_Success.wav': '奇迹之冠 | 成功',
    'Bgm_Animation_1_1_LS_CS20_SC027_124_3_4_KiloAppear_MixV1.wav': '过场动画027 | 基洛出现',
    'Bgm_Animation_1_1_LS_CS20_SC028_HarpShow.wav': '过场动画028 | 竖琴秀',
    'Bgm_Animation_1_1_LS_CS20_SC028_HarpShow_AddPiano.wav': '过场动画028 | 竖琴秀 | 有钢琴',
    'Bgm_Animation_1_1_LS_CS20_SC030_DragonLeave_MixV1.wav': '过场动画030 | 蓝龙离开',
    'Bgm_Animation_1_1_LS0100_SC010_DownHill_VNTA.wav': '过场动画010 | 飘下山坡',
    'Bgm_Animation_1_3_LS_CS20_SC005_FishShow.wav': '过场动画005 | 鱼暴走',
    'Bgm_Animation_1_3_LS_CS20_SC006_End.wav': '过场动画006 | 结束',
    'Bgm_Animation_1_5_LS_CS20_SC010_WishGoblin_230629.wav': '过场动画010 | 心愿精灵',
    'Bgm_Animation_3_1_LS0100_SC212.wav': '过场动画212',
    'Bgm_Animation_Prologue_LS0100_SC002.wav': '过场动画002 | 序章',
    'Bgm_Animation_Prologue_LS0100_SC007.wav': '过场动画007 | 序章',
    'Bgm_Animation_Prologue_LS0100_SC008_P1.wav': '过场动画008 | 序章 | P1',
    'Bgm_Animation_Prologue_LS0100_SC008_P2.wav': '过场动画008 | 序章 | P2',
    'LS0100_SC001_bgm.wav': '过场动画001 | 序章',
    'LS0100_SC004_bgm.wav': '过场动画004 | 序章',
    'SingingDragon_QiYuanShuLin_LS0100_SC115P.wav': '过场动画115P | 唱诗蓝龙 | 故乡的风&星愿之声 | 01',
    'SingingDragon_QiYuanShuLin_LS0100_SC115Q.wav': '过场动画115Q | 唱诗蓝龙 | 故乡的风&星愿之声 | 02',
    'SingingDragon_QiYuanShuLin_LS0100_SC115R.wav': '过场动画115R | 唱诗蓝龙 | 故乡的风&星愿之声 | 03',
    'SingingDragon_QiYuanShuLin_LS0100_SC115S.wav': '过场动画115S | 唱诗蓝龙 | 故乡的风&星愿之声 | 04',
    'SingingDragon_QiYuanShuLin_LS0100_SC115T.wav': '过场动画115T | 唱诗蓝龙 | 故乡的风&星愿之声 | 05',
    'SingingDragon_QiYuanShuLin_LS0100_SC115U.wav': '过场动画115U | 唱诗蓝龙 | 故乡的风&星愿之声 | 06',
    'SingingDragon_QiYuanShuLin_LS0100_SC115V.wav': '过场动画115V | 唱诗蓝龙 | 故乡的风&星愿之声 | 07',
    'SingingDragon_QiYuanShuLin_LS0100_SC115W.wav': '过场动画115W | 唱诗蓝龙 | 故乡的风&星愿之声 | 08',
    'SingingBlueDragon_WishTown_1.wav': '过场动画115A | 唱诗蓝龙 | 祈愿新生 | 01',
    'SingingBlueDragon_WishTown_2.wav': '过场动画115B | 唱诗蓝龙 | 祈愿新生 | 02',
    'SingingBlueDragon_WishTown_3.wav': '过场动画115C | 唱诗蓝龙 | 祈愿新生 | 03',
    'SingingBlueDragon_WishTown_4.wav': '过场动画115D | 唱诗蓝龙 | 祈愿新生 | 04',
    'SingingBlueDragon_WishTown_5.wav': '过场动画115E | 唱诗蓝龙 | 祈愿新生 | 05',
    'SingingBlueDragon_WishTown_6.wav': '过场动画115F | 唱诗蓝龙 | 祈愿新生 | 06',
    'SingingBlueDragon_WishTown_7.wav': '过场动画115G | 唱诗蓝龙 | 祈愿新生 | 07',
    'SingingBlueDragon_WishTown_8.wav': '过场动画115H | 唱诗蓝龙 | 祈愿新生 | 08',
    'Bgm_Animation_WishTown_LS0100_SC011.wav': '过场动画011',
    'Bgm_Animation_WishTown_LS0100_SC012.wav': '过场动画012',
    'Bgm_Animation_WishTown_LS0100_SC012_HeartBeat.wav': '过场动画012 | 心跳',
    'Bgm_Animation_WishTown_LS0100_SC013.wav': '过场动画013',
    'Bgm_Animation_WishTown_LS0100_SC014.wav': '过场动画014',
    'Bgm_Animation_WishTown_LS0100_SC015.wav': '过场动画015',
    'Bgm_Animation_WishTown_LS0100_SC016.wav': '过场动画016',
    'Bgm_Animation_WishTown_LS0100_SC017.wav': '过场动画017',
    'Bgm_Animation_WishTown_LS0100_SC018.wav': '过场动画018',
    'Bgm_Animation_WishTown_LS0100_SC026.wav': '过场动画026',
    'Bgm_Animation_WishTown_LS0100_SC027.wav': '过场动画027',
    'Bgm_Animation_WishTown_LS0100_SC030.wav': '过场动画030',
    'Bgm_Animation_WishTown_LS0100_SC032-062424.wav': '过场动画032',
    'Bgm_Animation_WishTown_LS0100_SC034_v2.wav': '过场动画034 | V2',
    'BGM_Boss_TanLanQiuNiao_EndingLS_98_4_4.wav': '贪婪囚鸟Boss战 | 结束',
    'BGM_Boss_TanLanQiuNiao_Intro_Loop_98_4_4.wav': '贪婪囚鸟Boss战 | 开场&循环',
    'BGM_Boss_TanLanQiuNiao_P2_98to106_4_4.wav': '贪婪囚鸟Boss战 | 二阶段',
    'BGM_Combat_General_Intro_V1_5_4_164.wav': '一般战斗 | 开场 | V1',
    'BGM_Combat_General_Intro_V2_5_4_164.wav': '一般战斗 | 开场 | V2',
    'BGM_Combat_General_Intro_V3_5_4_164.wav': '一般战斗 | 开场 | V3',
    'BGM_Combat_General_Intro_V4_5_4_164.wav': '一般战斗 | 开场 | V4',
    'BGM_Combat_General_Loop_164.wav': '一般战斗 | 循环',
    'BGM_Scene_Qiyuanshulin_Combat_MutantVine_bpm78_m44.wav': '变异树藤 | 战斗',
    'BGM_Scene_Qiyuanshulin_Normal_MutantVine_bpm78_m44.wav': '变异树藤 | 正常',
    'BGM_Battle_Stoneboss_Step1_125_4_4.wav': '巨石岩仔Boss战 | 第一阶段',
    'BGM_Battle_Stoneboss_Step2_Intro_130_4_4.wav': '巨石岩仔Boss战 | 第二阶段 | 开场',
    'BGM_Battle_Stoneboss_Step2_Loop_130_4_4.wav': '巨石岩仔Boss战 | 第二阶段 | 循环',
    'BGM_Battle_Stoneboss_Step2_Outro_130_4_4.wav': '巨石岩仔Boss战 | 第二阶段 | 结束',
    'BGM_CleanAnimal_End_80_4_4.wav': '能力 | 清洁 | 结束',
    'BGM_CleanAnimal_Loop_80_4_4.wav': '能力 | 清洁 | 循环',
    'BGM_System_ClothingDisplay_New_General_Lose.wav': '搭配比拼展示 | 新 | 失败',
    'BGM_System_ClothingDisplay_New_General_Main_110_3_4.wav': '搭配比拼展示 | 新 | 主旋律',
    'BGM_System_ClothingDisplay_New_General_Win.wav': '搭配比拼展示 | 新 | 胜利',
    'Bgm_Fishing_Normal_L3_Full_New.wav': '能力 | 钓鱼 | L3 | 完整',
    'BGM_LegendAnimal_Swan_End_65_4_4.wav': '',
    'BGM_LegendAnimal_Swan_Loop_65_4_4.wav': '',
    'BGM_LegendAnimal_Swan_Loop_Bell_1_65_4_4.wav': '',
    'BGM_LegendAnimal_Swan_Loop_Bell_2_65_4_4.wav': '',
    'BGM_LegendAnimal_Swan_Main_65_4_4.wav': '传奇生灵·巡星天鹅 | 主旋律',
    'BGM_LegendAnimal_Swan_Soar_65_4_4.wav': '传奇生灵·巡星天鹅 | 翱翔',
    'Bgm_LS_DelicateSwan_Performance_Meet.wav': '传奇生灵·巡星天鹅 | 初见',
    'Bgm_LS_DelicateSwan_Performance_Takeoff_0805.wav': '',
    'BGM_Game_Chasestars_120_4_4.wav': '游戏·追逐奇想星',
    'BGM_Game_Collectstars_123_4_4.wav': '游戏·收集星星',
    'BGM_Game_Findstar_120_4_4.wav': '游戏·寻找星形',
    'BGM_Game_GetPoints_125_4_4.wav': '游戏·得分游戏',
    'BGM_Game_Timelimitarrival_136_4_4.wav': '游戏·限时到达',
    'BGM_BoxGame_PaperCrane_170_3_4.wav': '游戏·飞翔的纸鹤',
    'BGM_BoxGame_Pinball_180_2_4.wav': '游戏·弹射球王',
    'BGM_Boxgame_RockPlant_NestingDoll_Intro_bpm120_m34.wav': '游戏·真假单品灵 | 开场',
    'BGM_Boxgame_RockPlant_NestingDoll_Loop_bpm120_m34.wav': '游戏·真假单品灵 | 循环',
    'BGM_Boxgame_RockPlant_NestingDoll_Lose_ChangeBPM_m34.wav': '',
    'BGM_Boxgame_RockPlant_NestingDoll_Victory_ChangeBPM_m34.wav': '',
    'BGM_Boxgame_RockPlant_NestingDoll_Win_ChangeBPM_m34.wav': '',
    'BGM_MiniGame_RockPlant_Dance_Lose_100_5_2.wav': '',
    'BGM_MiniGame_RockPlant_Dance_Main_100_5_2.wav': '游戏·欢乐热舞团 | 主旋律',
    'BGM_MiniGame_RockPlant_Dance_Win_100_5_2.wav': '',
    'BGM_UI_MiniGames_DuckRun_Intro_80_4_4.wav': '游戏·美鸭梨快跑 | 开场',
    'BGM_UI_MiniGames_DuckRun_Loop_Normal_80_4_4.wav': '游戏·美鸭梨快跑 | 循环',
    'BGM_UI_MiniGames_DuckRun_Loop_Speedup_80_4_4.wav': '游戏·美鸭梨快跑 | 加速',
    'BGM_UI_MiniGames_DuckRun_Loop_Waiting_80_4_4.wav': '游戏·美鸭梨快跑 | 等待',
    'BGM_Mirror_Challenge1_Loop_89_4_4.wav': '奇迹之冠 | 挑战1 | 循环',
    'BGM_Mirror_Challenge2_Intro_89_4_4.wav': '奇迹之冠 | 挑战2 | 开场',
    'BGM_Mirror_Challenge2_Loop_89_4_4.wav': '奇迹之冠 | 挑战2 | 循环',
    'Mirror_Challenge_DressTower_Opening.wav': '奇迹之冠 | 召开',
    'Mirror_Challenge_DressTower_Victory.wav': '奇迹之冠 | 夺冠',
    'BGM_Scene_Indoor_PuzzleSolvingRooom_Intro_Mastered_ChangeBPM.wav': '谜题空间 | 开场',
    'BGM_Scene_Indoor_PuzzleSolvingRooom_Loop_Mastered_ChangeBPM.wav': '谜题空间 | 循环',
    'Bgm_Scene_Shishutian_Train_01_bpm88_m44.wav': '愿望列车 | 呜呜列车 | 01',
    'Bgm_Scene_Shishutian_Train_02_bpm100_m44.wav': '愿望列车 | 呜呜列车 | 02',
    'BGM_Scene_Dongchashengtang_ChangeBPM.wav': '洞察圣堂 | 过渡用',
    'BGM_Scene_Indoor_InsightSanctuary_New_ChangeBPM.wav': '洞察圣堂 | 新 | 过渡用',
    'BGM_Scene_Lvye_WeddingPlace_60_4_4.wav': '天鹅羽亭',
    'BGM_Scene_Cave_GaintSnakeCave.wav': '',
    'BGM_Scene_Cave_QueenRelicCave.wav': '',
    'BGM_Scene_Cave_WishTownCaveGeneral.wav': '洞窟 | 心愿原野',
    'BGM_SceneYijiqu_ChangeBPM_Demo.wav': '微风绿野·遗迹区 | 过渡用',
    'BGM_Scene_GreenField_Caifengjidi_Night1_80_3_4.wav': '西西亚设计学院采风基地 | 夜晚 | 01',
    'BGM_Scene_GreenField_Caifengjidi_Night2_ChangeBPM.wav': '西西亚设计学院采风基地 | 夜晚 | 02',
    'BGM_Scene_GreenField_Huodongzhongxin_Day_Long_ChangeBPM.wav': '绿野活动支援中心 | 白天 | 长',
    'BGM_Scene_GreenField_Huodongzhongxin_Night_Long_ChangeBPM.wav': '绿野活动支援中心 | 夜晚 | 长',
    'BGM_Scene_GreenField_QueenRelicOutside_ChangeBPM.wav': '菲洛米亚女王行宫遗迹 | 外部',
    'BGM_Scene_GreenField_Buchongxiaowu_Day.wav': '捕虫小屋 | 白天',
    'BGM_Scene_GreenField_Buchongxiaowu_Night.wav': '捕虫小屋 | 夜晚',
    'BGM_Scene_GreenField_FA_Day.wav': '悠悠垂钓协会花愿镇分部 | 白天',
    'BGM_Scene_GreenField_Port_Day.wav': '绿野货运码头 | 白天',
    'BGM_Scene_GreenField_Port_Night.wav': '绿野货运码头 | 夜晚',
    'BGM_Scene_Border_50_4_4.wav': '筑心王国边境哨所',
    'BGM_Scene_GreenField_QueenRelic_Day_1_78_3_4.wav.wav': '菲洛米亚女王行宫遗迹 | 白天 | 01',
    'BGM_Scene_GreenField_QueenRelic_Day_1_Rain_78_3_4.wav': '菲洛米亚女王行宫遗迹 | 白天 | 01 | 雨天',
    'BGM_Scene_GreenField_QueenRelic_Day_2_78_3_4.wav.wav': '菲洛米亚女王行宫遗迹 | 白天 | 02',
    'BGM_Scene_GreenField_QueenRelic_Day_2_Rain_78_3_4.wav.wav': '菲洛米亚女王行宫遗迹 | 白天 | 02 | 雨天',
    'BGM_Scene_GreenField_QueenRelic_Night_1_65_3_4.wav': '菲洛米亚女王行宫遗迹 | 夜晚 | 01',
    'BGM_Scene_GreenField_QueenRelic_Night_1_Rain_65_3_4.wav': '菲洛米亚女王行宫遗迹 | 夜晚 | 01 | 雨天',
    'BGM_Scene_GreenField_QueenRelic_Night_2_65_3_4.wav': '菲洛米亚女王行宫遗迹 | 夜晚 | 02',
    'BGM_Scene_GreenField_QueenRelic_Night_2_Rain_65_3_4.wav': '菲洛米亚女王行宫遗迹 | 夜晚 | 02 | 雨天',
    'BGM_Scene_RebelCamp_Day_1_BPM120_Rainy.wav': '废弃疯愿之子营地 | 白天 | 01 | 雨天',
    'BGM_Scene_RebelCamp_Day_2_BPM120.wav': '废弃疯愿之子营地 | 白天 | 02',
    'BGM_Scene_RebelCamp_Day_2_BPM120_Rainy.wav': '废弃疯愿之子营地 | 白天 | 02 | 雨天',
    'BGM_Scene_Map01_Wild_Day_01_Rainy.wav': '花愿镇·野外 | 白天 | 01 | 雨天',
    'BGM_Scene_Map01_Wild_Day_02_Rainy.wav': '花愿镇·野外 | 白天 | 02 | 雨天',
    'BGM_Scene_Map01_Wild_Day_03_Rainy.wav': '花愿镇·野外 | 白天 | 03 | 雨天',
    'BGM_Scene_Map01_Wild_Day_04_Rainy.wav': '花愿镇·野外 | 白天 | 04 | 雨天',
    'BGM_Scene_Map01_Wild_Day_05_Rainy.wav': '花愿镇·野外 | 白天 | 05 | 雨天',
    'BGM_Scene_Map01_Wild_Day_06_Rainy.wav': '花愿镇·野外 | 白天 | 06 | 雨天',
    'BGM_Scene_Map01_Wild_Day_07_Rainy.wav': '花愿镇·野外 | 白天 | 07 | 雨天',
    'BGM_Scene_Map01_Wild_Day_08_Rainy.wav': '花愿镇·野外 | 白天 | 08 | 雨天',
    'BGM_Scene_Map01_Wild_Day_09_Rainy.wav': '花愿镇·野外 | 白天 | 09 | 雨天',
    'BGM_Scene_Map01_Wild_Day_10_Rainy_bpm50.wav': '花愿镇·野外 | 白天 | 10 | 雨天',
    'BGM_Scene_Map01_Wild_Day_11_Rainy_bpm48.wav': '花愿镇·野外 | 白天 | 11 | 雨天',
    'BGM_Scene_Map01_Wild_Day_12_Rainy_bpm56.wav': '花愿镇·野外 | 白天 | 12 | 雨天',
    'BGM_Scene_Map01_Wild_Day_13_Rainy_bpm44.wav': '花愿镇·野外 | 白天 | 13 | 雨天',
    'BGM_Scene_Map01_Wild_Day_01_Sunny.wav': '花愿镇·野外 | 白天 | 01 | 晴天',
    'BGM_Scene_Map01_Wild_Day_02_Sunny.wav': '花愿镇·野外 | 白天 | 02 | 晴天',
    'BGM_Scene_Map01_Wild_Day_03_Sunny.wav': '花愿镇·野外 | 白天 | 03 | 晴天',
    'BGM_Scene_Map01_Wild_Day_04_Sunny.wav': '花愿镇·野外 | 白天 | 04 | 晴天',
    'BGM_Scene_Map01_Wild_Day_05_Sunny.wav': '花愿镇·野外 | 白天 | 05 | 晴天',
    'BGM_Scene_Map01_Wild_Day_06_Sunny.wav': '花愿镇·野外 | 白天 | 06 | 晴天',
    'BGM_Scene_Map01_Wild_Day_07_Sunny.wav': '花愿镇·野外 | 白天 | 07 | 晴天',
    'BGM_Scene_Map01_Wild_Day_08_Sunny.wav': '花愿镇·野外 | 白天 | 08 | 晴天',
    'BGM_Scene_Map01_Wild_Day_09_Sunny.wav': '花愿镇·野外 | 白天 | 09 | 晴天',
    'BGM_Scene_Map01_Wild_Day_10_Sunny_bpm50.wav': '花愿镇·野外 | 白天 | 10 | 晴天',
    'BGM_Scene_Map01_Wild_Day_11_Sunny_bpm48.wav': '花愿镇·野外 | 白天 | 11 | 晴天',
    'BGM_Scene_Map01_Wild_Day_12_Sunny_bpm56.wav': '花愿镇·野外 | 白天 | 12 | 晴天',
    'BGM_Scene_Map01_Wild_Day_13_Sunny_bpm44.wav': '花愿镇·野外 | 白天 | 13 | 晴天',
    'BGM_Scene_Map01_Wild_Night_01_Rainy.wav': '花愿镇·野外 | 夜晚 | 01 | 雨天',
    'BGM_Scene_Map01_Wild_Night_02_Rainy.wav': '花愿镇·野外 | 夜晚 | 02 | 雨天',
    'BGM_Scene_Map01_Wild_Night_03_Rainy.wav': '花愿镇·野外 | 夜晚 | 03 | 雨天',
    'BGM_Scene_Map01_Wild_Night_04_Rainy.wav': '花愿镇·野外 | 夜晚 | 04 | 雨天',
    'BGM_Scene_Map01_Wild_Night_05_Rainy.wav': '花愿镇·野外 | 夜晚 | 05 | 雨天',
    'BGM_Scene_Map01_Wild_Night_06_Rainy.wav': '花愿镇·野外 | 夜晚 | 06 | 雨天',
    'BGM_Scene_Map01_Wild_Night_07_Rainy.wav': '花愿镇·野外 | 夜晚 | 07 | 雨天',
    'BGM_Scene_Map01_Wild_Night_08_Rainy.wav': '花愿镇·野外 | 夜晚 | 08 | 雨天',
    'BGM_Scene_Map01_Wild_Night_09_Rainy.wav': '花愿镇·野外 | 夜晚 | 09 | 雨天',
    'BGM_Scene_Map01_Wild_Night_10_Rainy_bpm76.wav': '花愿镇·野外 | 夜晚 | 10 | 雨天',
    'BGM_Scene_Map01_Wild_Night_11_Rainy_bpm88.wav': '花愿镇·野外 | 夜晚 | 11 | 雨天',
    'BGM_Scene_Map01_Wild_Night_12_Rainy_bpm62.wav': '花愿镇·野外 | 夜晚 | 12 | 雨天',
    'BGM_Scene_Map01_Wild_Night_01_Sunny.wav': '花愿镇·野外 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Map01_Wild_Night_02_Sunny.wav': '花愿镇·野外 | 夜晚 | 02 | 晴天',
    'BGM_Scene_Map01_Wild_Night_03_Sunny.wav': '花愿镇·野外 | 夜晚 | 03 | 晴天',
    'BGM_Scene_Map01_Wild_Night_04_Sunny.wav': '花愿镇·野外 | 夜晚 | 04 | 晴天',
    'BGM_Scene_Map01_Wild_Night_05_Sunny.wav': '花愿镇·野外 | 夜晚 | 05 | 晴天',
    'BGM_Scene_Map01_Wild_Night_06_Sunny.wav': '花愿镇·野外 | 夜晚 | 06 | 晴天',
    'BGM_Scene_Map01_Wild_Night_07_Sunny.wav': '花愿镇·野外 | 夜晚 | 07 | 晴天',
    'BGM_Scene_Map01_Wild_Night_08_Sunny.wav': '花愿镇·野外 | 夜晚 | 08 | 晴天',
    'BGM_Scene_Map01_Wild_Night_09_Sunny.wav': '花愿镇·野外 | 夜晚 | 09 | 晴天',
    'BGM_Scene_Map01_Wild_Night_10_Sunny_bpm76.wav': '花愿镇·野外 | 夜晚 | 10 | 晴天',
    'BGM_Scene_Map01_Wild_Night_11_Sunny_bpm88.wav': '花愿镇·野外 | 夜晚 | 11 | 晴天',
    'BGM_Scene_Map01_Wild_Night_12_Sunny_bpm62.wav': '花愿镇·野外 | 夜晚 | 12 | 晴天',
    'BGM_Scene_GreenField_General_Day_Long_1_81_4_4.wav': '微风绿野·野外 | 白天 | 长 | 01',
    'BGM_Scene_GreenField_General_Day_Long_2_91_3_4.wav': '微风绿野·野外 | 白天 | 长 | 02',
    'BGM_Scene_GreenField_General_Day_Short_1.wav': '微风绿野·野外 | 白天 | 短 | 01',
    'BGM_Scene_GreenField_General_Day_Short_2.wav': '微风绿野·野外 | 白天 | 短 | 02',
    'BGM_Scene_GreenField_General_Day_Short_3.wav': '微风绿野·野外 | 白天 | 短 | 03',
    'BGM_Scene_GreenField_General_Day_Short_4.wav': '微风绿野·野外 | 白天 | 短 | 04',
    'BGM_Scene_GreenField_General_Day_Short_5.wav': '微风绿野·野外 | 白天 | 短 | 05',
    'BGM_Scene_GreenField_General_Day_Short_6.wav': '微风绿野·野外 | 白天 | 短 | 06',
    'BGM_Scene_GreenField_General_Day_Short_7.wav': '微风绿野·野外 | 白天 | 短 | 07',
    'BGM_Scene_GreenField_General_Day_Short_8.wav': '微风绿野·野外 | 白天 | 短 | 08',
    'BGM_Scene_GreenField_General_Day_Short_9.wav': '微风绿野·野外 | 白天 | 短 | 09',
    'BGM_Scene_GreenField_General_Day_Long_1_Rainy.wav': '微风绿野·野外 | 白天 | 长 | 01 | 雨天',
    'BGM_Scene_GreenField_General_Day_Long_2_Rainy.wav': '微风绿野·野外 | 白天 | 长 | 02 | 雨天',
    'BGM_Scene_GreenField_General_Day_Short_1_Rainy.wav': '微风绿野·野外 | 白天 | 短 | 01 | 雨天',
    'BGM_Scene_GreenField_General_Day_Short_2_Rainy.wav': '微风绿野·野外 | 白天 | 短 | 02 | 雨天',
    'BGM_Scene_GreenField_General_Day_Short_3_Rainy.wav': '微风绿野·野外 | 白天 | 短 | 03 | 雨天',
    'BGM_Scene_GreenField_General_Day_Short_4_Rainy.wav': '微风绿野·野外 | 白天 | 短 | 04 | 雨天',
    'BGM_Scene_GreenField_General_Day_Short_5_Rainy.wav': '微风绿野·野外 | 白天 | 短 | 05 | 雨天',
    'BGM_Scene_GreenField_General_Day_Short_6_Rainy.wav': '微风绿野·野外 | 白天 | 短 | 06 | 雨天',
    'BGM_Scene_GreenField_General_Day_Short_7_Rainy.wav': '微风绿野·野外 | 白天 | 短 | 07 | 雨天',
    'BGM_Scene_GreenField_General_Day_Short_8_Rainy.wav': '微风绿野·野外 | 白天 | 短 | 08 | 雨天',
    'BGM_Scene_GreenField_General_Day_Short_9_Rainy.wav': '微风绿野·野外 | 白天 | 短 | 09 | 雨天',
    'BGM_Scene_GreenField_General_Night_Short_1_Rainy.wav': '微风绿野·野外 | 夜晚 | 短 | 01 | 雨天',
    'BGM_Scene_GreenField_General_Night_Short_2_Rainy.wav': '微风绿野·野外 | 夜晚 | 短 | 02 | 雨天',
    'BGM_Scene_GreenField_General_Night_Short_3_Rainy.wav': '微风绿野·野外 | 夜晚 | 短 | 03 | 雨天',
    'BGM_Scene_GreenField_General_Night_Short_4_Rainy.wav': '微风绿野·野外 | 夜晚 | 短 | 04 | 雨天',
    'BGM_Scene_GreenField_General_Night_Short_5_Rainy.wav': '微风绿野·野外 | 夜晚 | 短 | 05 | 雨天',
    'BGM_Scene_GreenField_General_Night_Short_6_Rainy.wav': '微风绿野·野外 | 夜晚 | 短 | 06 | 雨天',
    'BGM_Scene_GreenField_General_Night_Short_7_Rainy.wav': '微风绿野·野外 | 夜晚 | 短 | 07 | 雨天',
    'BGM_Scene_GreenField_General_Night_Short_8_Rainy.wav': '微风绿野·野外 | 夜晚 | 短 | 08 | 雨天',
    'BGM_Scene_GreenField_General_Night_Short_9_Rainy.wav': '微风绿野·野外 | 夜晚 | 短 | 09 | 雨天',
    'BGM_Scene_Map01_RuinsHill_Day_01_Rainy_bpm56_m34.wav': '遗迹山坡 | 白天 | 01 | 雨天',
    'BGM_Scene_Map01_RuinsHill_Day_02_Rainy_bpm60_m34.wav': '遗迹山坡 | 白天 | 02 | 雨天',
    'BGM_Scene_Map01_RuinsHill_Day_03_Rainy_bpm69_m34.wav': '遗迹山坡 | 白天 | 03 | 雨天',
    'BGM_Scene_Map01_RuinsHill_Day_01_Sunny_bpm56_m34.wav': '遗迹山坡 | 白天 | 01 | 晴天',
    'BGM_Scene_Map01_RuinsHill_Day_02_Sunny_bpm60_m34.wav': '遗迹山坡 | 白天 | 02 | 晴天',
    'BGM_Scene_Map01_RuinsHill_Day_03_Sunny_bpm69_m34.wav': '遗迹山坡 | 白天 | 03 | 晴天',
    'BGM_Scene_Map01_RuinsHill_Night_01_Rainy_bpm52_m34.wav': '遗迹山坡 | 夜晚 | 01 | 雨天',
    'BGM_Scene_Map01_RuinsHill_Night_02_Rainy_bpm44_m34.wav': '遗迹山坡 | 夜晚 | 02 | 雨天',
    'BGM_Scene_Map01_RuinsHill_Night_03_Rainy_bpm44_m34.wav': '遗迹山坡 | 夜晚 | 03 | 雨天',
    'BGM_Scene_Map01_RuinsHill_Night_01_Sunny_bpm52_m34.wav': '遗迹山坡 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Map01_RuinsHill_Night_02_Sunny_bpm44_m34.wav': '遗迹山坡 | 夜晚 | 02 | 晴天',
    'BGM_Scene_Map01_RuinsHill_Night_03_Sunny_bpm44_m34.wav': '遗迹山坡 | 夜晚 | 03 | 晴天',
    'BGM_Scene_LegendAnimal_WhiteCow_Inside_Day_Clean_ChangeBPM.wav': '传奇生灵·宴席白牛 | 栖息地内 | 白天 | 已清洁',
    'BGM_Scene_LegendAnimal_WhiteCow_Inside_Day_Crazy_Intro_ChangeBPM.wav': '传奇生灵·宴席白牛 | 栖息地内 | 白天 | 未清洁 | 开场',
    'BGM_Scene_LegendAnimal_WhiteCow_Inside_Day_Crazy_Loop_105_4_4.wav': '传奇生灵·宴席白牛 | 栖息地内 | 白天 | 未清洁 | 循环',
    'BGM_Scene_LegendAnimal_WhiteCow_Inside_Night_Loop_95_4_4.wav': '传奇生灵·宴席白牛 | 栖息地内 | 夜晚 | 循环',
    'BGM_Scene_LegendAnimal_WhiteCow_Outside_ChangeBPM.wav': '传奇生灵·宴席白牛 | 栖息地外',
    'BGM_Scene_LegendAnimal_Swan_1.wav': '',
    'BGM_Scene_LegendAnimal_Swan_2.wav': '',
    'BGM_Scene_LegendAnimal_Swan_3.wav': '',
    'BGM_Scene_LegendAnimal_Swan_4.wav': '',
    'BGM_Scene_Challenge_AdvancedTable_New_ChangeBPM.wav': '挑战 | 进阶 | 新 | 过渡用',
    'BGM_Scene_Indoor_Chenxilvguan_125_3_4_MixV1.wav': '小绵菊旅馆 | V1',
    'BGM_Scene_Indoor_Dapeishixiehui_120_3_4_MixV1.wav': '搭配师协会 | V1',
    'BGM_Scene_Indoor_Guangyufeiniaocanting_Day_130_ChangeBPM_4_4_MixV1.wav': '光与飞鸟餐厅 | 白天 | V1',
    'BGM_Scene_Indoor_Guangyufeiniaocanting_Night_104_4_4.wav': '光与飞鸟餐厅 | 夜晚',
    'BGM_Scene_Indoor_InfinityMirror_ChangeBPM.wav': '无限之镜 | 过渡用',
    'BGM_Scene_Indoor_Marksclothingshop_Day_108_3_4_MixV1.wav': '马尔克斯服装店 | 白天 | V1',
    'BGM_Scene_Indoor_Marksclothingshop_Night_60_4_4.wav': '马尔克斯服装店 | 夜晚',
    'BGM_Scene_Indoor_Minju_Day_102_3_4_Update.wav': '民居 | 白天',
    'BGM_Scene_Indoor_Minju_Night_64_4_4_Update.wav': '民居 | 夜晚',
    'BGM_Scene_Indoor_Nuonuoyizhijia_70_4_4.wav': '诺诺依的家',
    'BGM_Scene_Indoor_LimaoClub.wav': '围兜狸猫欢笑俱乐部',
    'BGM_Scene_Indoor_LimaoClub_Reverb.wav': '围兜狸猫欢笑俱乐部 | 混响',
    'BGM_Scene_WishTown_Backmountain_Day_A1.wav': '花愿镇后山 | 白天 | A1',
    'BGM_Scene_WishTown_Backmountain_Day_A2.wav': '花愿镇后山 | 白天 | A2',
    'BGM_Scene_WishTown_Backmountain_Night_A1.wav': '花愿镇后山 | 夜晚 | A1',
    'BGM_Scene_WishTown_Backmountain_Night_A2.wav': '花愿镇后山 | 夜晚 | A2',
    'BGM_Scene_WishTown_East_Day_A1.wav': '花愿镇河东 | 白天 | A1',
    'BGM_Scene_WishTown_East_Day_A2.wav': '花愿镇河东 | 白天 | A2',
    'BGM_Scene_WishTown_East_Night_A1.wav': '花愿镇河东 | 夜晚 | A1',
    'BGM_Scene_WishTown_East_Night_A2.wav': '花愿镇河东 | 夜晚 | A2',
    'BGM_Scene_WishTown_Lakeside_Day_A1.wav': '裙摆湖畔 | 白天 | A1',
    'BGM_Scene_WishTown_Lakeside_Day_A2.wav': '裙摆湖畔 | 白天 | A2',
    'BGM_Scene_WishTown_Lakeside_Night_A1.wav': '裙摆湖畔 | 夜晚 | A1',
    'BGM_Scene_WishTown_Lakeside_Night_A2.wav': '裙摆湖畔 | 夜晚 | A2',
    'BGM_Scene_WishTown_West_Day_A1.wav': '花愿镇河西 | 白天 | A1',
    'BGM_Scene_WishTown_West_Day_A2.wav': '花愿镇河西 | 白天 | A2',
    'BGM_Scene_WishTown_West_Day_B1.wav': '花愿镇河西 | 白天 | B1',
    'BGM_Scene_WishTown_West_Day_B2.wav': '花愿镇河西 | 白天 | B2',
    'BGM_Scene_WishTown_West_Night_A1.wav': '花愿镇河西 | 夜晚 | A1',
    'BGM_Scene_WishTown_West_Night_A2.wav': '花愿镇河西 | 夜晚 | A2',
    'BGM_Scene_WishTown_Backmountain_Day_A1_Rainy.wav': '花愿镇后山 | 白天 | A1 | 雨天',
    'BGM_Scene_WishTown_Backmountain_Day_A2_Rainy.wav': '花愿镇后山 | 白天 | A2 | 雨天',
    'BGM_Scene_WishTown_Backmountain_Night_A1_Rainy.wav': '花愿镇后山 | 夜晚 | A1 | 雨天',
    'BGM_Scene_WishTown_Backmountain_Night_A2_Rainy.wav': '花愿镇后山 | 夜晚 | A2 | 雨天',
    'BGM_Scene_WishTown_East_Day_A1_Rainy.wav': '花愿镇河东 | 白天 | A1 | 雨天',
    'BGM_Scene_WishTown_East_Day_A2_Rainy.wav': '花愿镇河东 | 白天 | A2 | 雨天',
    'BGM_Scene_WishTown_East_Night_A1_Rainy.wav': '花愿镇河东 | 夜晚 | A1 | 雨天',
    'BGM_Scene_WishTown_East_Night_A2_Rainy.wav': '花愿镇河东 | 夜晚 | A2 | 雨天',
    'BGM_Scene_WishTown_Lakeside_Day_A1_Rainy.wav': '裙摆湖畔 | 白天 | A1 | 雨天',
    'BGM_Scene_WishTown_Lakeside_Day_A2_Rainy.wav': '裙摆湖畔 | 白天 | A2 | 雨天',
    'BGM_Scene_WishTown_Lakeside_Night_A1_Rainy.wav': '裙摆湖畔 | 夜晚 | A1 | 雨天',
    'BGM_Scene_WishTown_Lakeside_Night_A2_Rainy.wav': '裙摆湖畔 | 夜晚 | A2 | 雨天',
    'BGM_Scene_WishTown_West_Bright_Rainy_part1.wav': '花愿镇河西 | 白天 | 阳光 | 雨天 | 第1部分',
    'BGM_Scene_WishTown_West_Bright_Rainy_part2.wav': '花愿镇河西 | 白天 | 阳光 | 雨天 | 第2部分',
    'BGM_Scene_WishTown_West_Day_Rainy_part1.wav': '花愿镇河西 | 白天 | 雨天 | 第1部分',
    'BGM_Scene_WishTown_West_Day_Rainy_part2_v2.wav': '花愿镇河西 | 白天 | 雨天 | 第2部分',
    'BGM_Scene_WishTown_West_Night_Rainy_part1.wav': '花愿镇河西 | 夜晚 | 雨天 | 第1部分',
    'BGM_Scene_WishTown_West_Night_Rainy_part2.wav': '花愿镇河西 | 夜晚 | 雨天 | 第2部分',
    'BGM_Scene_Yewai_New_Night_1.wav': '花愿镇·野外 | 新 | 夜晚 | 01',
    'BGM_Scene_Yewai_New_Night_2.wav': '花愿镇·野外 | 新 | 夜晚 | 02',
    'BGM_Scene_Yewai_New_Night_3.wav': '花愿镇·野外 | 新 | 夜晚 | 03',
    'BGM_Scene_Yewai_New_Night_4.wav': '花愿镇·野外 | 新 | 夜晚 | 04',
    'BGM_Scene_Yewai_New_Night_5.wav': '花愿镇·野外 | 新 | 夜晚 | 05',
    'BGM_Scene_Yewai_New_Night_6.wav': '花愿镇·野外 | 新 | 夜晚 | 06',
    'BGM_Scene_Yewai_New_Night_7.wav': '花愿镇·野外 | 新 | 夜晚 | 07',
    'BGM_Scene_Yewai_New_Night_8.wav': '花愿镇·野外 | 新 | 夜晚 | 08',
    'BGM_Scene_Yewai_New_Night_9.wav': '花愿镇·野外 | 新 | 夜晚 | 09',
    'BGM_Scene_Qiyuanshulin_WishgodSong_Extra.wav': '愿望神之歌 | 加长',
    'BirdWhistle_Clarinet_1.wav': '',
    'BirdWhistle_Clarinet_2.wav': '',
    'BirdWhistle_Clarinet_3.wav': '',
    'BirdWhistle_Clarinet_4.wav': '',
    'BirdWhistle_Clarinet_5.wav': '',
    'BirdWhistle_Clarinet_6.wav': '',
    'BirdWhistle_Clarinet_7.wav': '',
    'Npc_Guitar_Caifengjidi_Version2.wav': 'NPC | 吉他 | 采风基地 | 版本2',
    'Npc_Lute_Version2.wav': 'NPC | 琉特琴 | 版本2',
    'Npc_Guitar_Lonely_DryMono.wav': 'NPC | 吉他 | 孤独 | 干式单声道',
    'Npc_Guitar_Play_DryMono.wav': 'NPC | 吉他 | 弹奏 | 干式单声道',
    'Npc_Piano_162_3_4_Dry.wav': 'NPC | 钢琴 | 干式',
    'KingParrot_Sing1.wav': '',
    'KingParrot_Sing2.wav': '',
    'KingParrot_Sing3.wav': '',
    'KingParrot_Sing4.wav': '',
    'KingParrot_Sing5.wav': '',
    'BGM_LS_BattlePass_Performance.wav': '奇迹之旅 | 大月卡、战令 | 演出',
    'BGM_Animation_Qiyuanshulin_LS0100_SC303.wav': '过场动画303',
    'BGM_Animation_Qiyuanshulin_LS0100_SC305.wav': '过场动画305',
    'BGM_Animation_Qiyuanshulin_LS0100_SC306.wav': '过场动画306',
    'Bgm_Animation_Qiyuanshulin_LS0100_SC307.wav': '过场动画307',
    'BGM_Animation_Qiyuanshulin_LS0100_SC308.wav': '过场动画308',
    'BGM_Animation_Qiyuanshulin_LS0100_SC309.wav': '过场动画309',
    'BGM_Animation_Qiyuanshulin_LS0100_SC311.wav': '过场动画311',
    'BGM_Animation_Qiyuanshulin_LS0100_SC313_Master.wav': '过场动画313',
    'BGM_Animation_Qiyuanshulin_LS0100_SC315.wav': '过场动画315',
    'BGM_Animation_Qiyuanshulin_LS0100_SC316.wav': '过场动画316',
    'Bgm_Animation_Qiyuanshulin_LS0100_SC317.wav': '过场动画317',
    'Bgm_Animation_Qiyuanshulin_LS0100_SC318.wav': '过场动画318',
    'BGM_Boss_Qigda_P1_OpenLS_136_4_4.wav': '奇格格达Boss战 | 开场',
    'BGM_Boss_Qigda_P2_EndingLS_136_4_4.wav': '奇格格达Boss战 | 收场',
    'BGM_Dialogue_E01_Easy_104_3_4.wav': '',
    'BGM_Dialogue_E02.1_Daily_112_4_4.wav': '',
    'BGM_Dialogue_E02.2_Daily_88_4_4.wav': '',
    'BGM_Dialogue_E02_Daily_74_4_4.wav': '',
    'BGM_Dialogue_E03.1_Funny_114_4_4.wav': '',
    'BGM_Dialogue_E03_Funny_96_4_4to3_4.wav': '',
    'BGM_Dialogue_E04_Tension_120_3_4.wav': '',
    'BGM_Dialogue_E05.1_Suspenseful_80_4_4.wav': '',
    'BGM_Dialogue_E05_Suspenseful_80_3_4.wav': '',
    'BGM_Dialogue_E08_Tense_96_4_4.wav': '',
    'BGM_Dialogue_E10.2_Warm_102_4_4.wav': '',
    'BGM_Dialogue_E10_Warm_122_3_4.wav': '',
    'BGM_Dialogue_E10_Warm_Exclusive.wav': '',
    'BGM_Dialogue_E11_Sad_98_4_4.wav': '',
    'BGM_Dialogue_Violin_01.wav': '小提琴 | 风和水滴的小调',
    'BGM_Dialogue_Violin_Ballade_of_Homeland_Fragment1_3.wav': '小提琴 | 归乡曲 | 片段',
    'BGM_Dialogue_Violin_Ballade_of_Homeland_FullwPno.wav': '小提琴 | 归乡曲 | 完整版',
    'BGM_Dialogue_Violin_Shishutian.wav': '小提琴 | 石树与飞花',
    'BGM_Plot_1_1_Room3_Intro_102_3_4_OutsideBegin_MixV1.wav': '副本·大世界 | 房间3 | 纪念山地 | 开场 | V1',
    'BGM_Plot_1_1_Room3_Loop_124_3_4_MixV1.wav': '副本·大世界 | 房间3 | 纪念山地 | 循环 | V1',
    'BGM_Plot_1_1_Room4_72_4_4_BlueDragonPark_MixV1.wav': '副本·大世界 | 房间4 | 古花愿镇纪念公园 | V1',
    'BGM_Plot_1_3_Room3_115_3_4.wav': '副本·福鸣之井 | 房间3',
    'BGM_Plot_1_3_Room4_1_110_4_4.wav': '副本·福鸣之井 | 房间4 | 1',
    'BGM_Plot_1_3_Room5_Intro_205_4_4.wav': '副本·福鸣之井 | 房间5 | 开场',
    'BGM_Plot_1_3_Room5_Loop_205_4_4.wav': '副本·福鸣之井 | 房间5 | 循环',
    'BGM_Plot_1_3_Room5_Outro_205_4_4.wav': '副本·福鸣之井 | 房间5 | 收场',
    'Plot_1_3_Dark_70_3_4.wav': '副本·福鸣之井 | 黑暗',
    'Plot_1_3_Room1&2_160_3_4.wav': '副本·福鸣之井 | 房间1&2',
    'Plot_1_3_Room4_2_V4_110_4_4.wav': '副本·福鸣之井 | 房间4 | 2 | V4',
    'BGM_Plot_1_5_Room1_72_4_4_RecMix_V1.wav': '副本·愿望梦境仓库 | 房间1 | V1',
    'BGM_Plot_1_5_Room2_72_4_4_RecMix_V1.wav': '副本·愿望梦境仓库 | 房间2 | V1',
    'BGM_Plot_1_5_Room4_Folded_Final1.wav': '副本·愿望梦境仓库 | 房间4 | 大纸鹤 | 最终版1',
    'BGM_Plot_1_5_Room5Final_72_4_4.wav': '副本·愿望梦境仓库 | 房间5 | 最终版',
    'Folded_FX.wav': '',
    'Folded_MMA_Cut.wav': '副本·愿望梦境仓库 | 房间4 | 大纸鹤 | 伴奏',
    'BGM_Plot_1_5_Room3_Intro_72_4_4.wav': '副本·愿望梦境仓库 | 房间3 | 开场',
    'BGM_Plot_1_5_Room3_Loop_72_4_4.wav': '副本·愿望梦境仓库 | 房间3 | 循环',
    'BGM_Plot_1_5_Room4Entrance_Intro_69_4_4.wav': '副本·愿望梦境仓库 | 房间4 | 开场',
    'BGM_Plot_1_5_Room4Entrance_Loop_69_4_4.wav.wav': '副本·愿望梦境仓库 | 房间4 | 循环',
    'BGM_Plot_1_5_Room5_72_4_4.wav': '副本·愿望梦境仓库 | 房间5',
    'Plot1_5Room4_FlyC_Loop_78_4_4_v2.wav': '副本·愿望梦境仓库 | 房间4 | 飞翔·普通版 | 循环 | V2',
    'BGM_Plot_2_1_Qianting_Music_NewMidi_80_4_4.wav': '',
    'BGM_Plot_2_1_Room6_Wangzuo_Changemarker_230703.wav': '',
    'Plot_2_1_GhostVoice_2.wav': '',
    'Plot_2_1_Room1&2_ChangeBPM.wav': '',
    'Plot_2_1_Room3_100_3_4.wav': '',
    'Plot_2_1_Room4_Intro_Music_130_3_4.wav': '',
    'Plot_2_1_Room4_Loop_Music_130_3_4.wav': '',
    'Plot_2_1_Room4_Loop_SVVocal_130_3_4.wav': '',
    'Plot_2_1_Room4_Loop_SVVocal_Reverb_130_3_4.wav': '',
    'Plot_2_1_Room5_132_4_4.wav': '',
    'Plot_2_1_Room6_Qianting_Vocal_80_4_4.wav': '',
    'Plot_2_1_Room6_Qianting_Vocal_Reverb_80_4_4.wav': '',
    'BGM_Plot_2_2_Room1_Quiet_144_3_4.wav': '',
    'BGM_Plot_2_2_Room2_2_160_3_4_Comp.wav': '',
    'BGM_Plot_2_2_Room3_Intro_LS_170_3_4.wav': '',
    'BGM_Plot_2_2_Room3_Oneshot_170_3_4_Comp.wav': '',
    'BGM_Plot_2_2_Room4_Entrance_ChangeBPM_Comp.wav': '',
    'BGM_Plot_2_2_Room4_Loop_Comp.wav': '',
    'BGM_Plot_2_2_Room5_Full_92_3_4_Comp.wav': '',
    'Plot2_2Room2_1Entrance_92_4_4.wav': '',
    'Plot2_2Room2_1_Loop_160_3_4.wav': '',
    'Plot2_2Room2_1_LS_160_2_4.wav': '',
    'Plot2_2_Room1_144_3_4.wav': '',
    'BGM_Plot_3_1_Room1_IntroRoom_110_3_4.wav': '副本·涟漪之窖 | 房间1 | 开场房间',
    'BGM_Plot_3_1_Room2_Transporter_v2_146_3_4.wav': '副本·涟漪之窖 | 房间2 | 运输通道',
    'BGM_Plot_3_1_Room3_Transporter_TensionVersion_146_3_4.wav.wav': '副本·涟漪之窖 | 房间3 | 运输通道 | 紧张版',
    'BGM_Plot_3_1_Room4_Waterfalls_Long_ChangeBPM.wav.wav': '副本·涟漪之窖 | 房间4 | 珍酿仓库·瀑布 | 过渡用',
    'BGM_Plot_3_1_Room5_Pontoon_100_3_4.wav': '副本·涟漪之窖 | 房间5 | 珍酿仓库·浮桶',
    'BGM_Plot_3_1_Room6_Office_110_3_4.wav': '副本·涟漪之窖 | 房间6 | 办公室',
    'BGM_Plot_3_1_Room7_Battle_146_4_4.wav': '副本·涟漪之窖 | 房间7 | 战斗',
    'Bgm3_2_Room5Entrance_140_4_4.wav': '副本·幽灵列车 | 房间5 | 进入',
    'Bgm_Animation_3_2_LS0100_SC223.wav': '过场动画223',
    'Bgm_Animation_3_2_LS_0100_SC217.wav': '过场动画217',
    'Bgm_Animation_3_2_LS_0100_SC219.wav': '过场动画219',
    'Plot3_2_Room1_Intro_80_3_4.wav': '副本·幽灵列车 | 房间1 | 开场',
    'Plot3_2_Room1_Loop_80_3_4.wav': '副本·幽灵列车 | 房间1 | 循环',
    'Plot3_2_Room2_Intro_ChangeBPM.wav': '副本·幽灵列车 | 房间2 | 开场 | 过渡用',
    'Plot3_2_Room2_Loop_130_4_4.wav': '副本·幽灵列车 | 房间2 | 循环',
    'Plot3_2_Room3_Loop_130_4_4.wav': '副本·幽灵列车 | 房间3 | 循环',
    'Plot3_2_Room4_Intro_80_6_8.wav': '副本·幽灵列车 | 房间4 | 开场',
    'Plot3_2_Room4_Loop_80_6_8.wav': '副本·幽灵列车 | 房间4 | 循环',
    'Plot3_2_Room5_Intro_150_4_4.wav': '副本·幽灵列车 | 房间5 | 开场',
    'Plot3_2_Room5_Loop_NewDrums_150_4_4.wav': '副本·幽灵列车 | 房间5 | 循环 | 新版有架子鼓',
    'BGM_Animation_4_1_LS_0100_SC304.wav': '过场动画304',
    'BGM_Plot_4_1_Room1Intro_ChangeBPM.wav': '副本·缇米丝的美妆工坊 | 房间1 | 开场',
    'BGM_Plot_4_1_Room1Loop_82_4_4.wav': '副本·缇米丝的美妆工坊 | 房间1 | 循环',
    'BGM_Plot_4_1_Room1Loop_TrackCombine_Transmit_Reverse_82_4 _4.wav': '副本·缇米丝的美妆工坊 | 房间1 | 循环 | 反向',
    'BGM_Plot_4_1_Room2Intro_ChangeBPM.wav': '副本·缇米丝的美妆工坊 | 房间2 | 开场',
    'BGM_Plot_4_1_Room2Loop_105_4_4.wav': '副本·缇米丝的美妆工坊 | 房间2 | 循环',
    'BGM_Plot_4_1_Room3Loop_100_4_4.wav': '副本·缇米丝的美妆工坊 | 房间3 | 循环',
    'BGM_Plot_4_1_Room3Loop_Transmit_ForwadDirection_100_4_4.wav': '副本·缇米丝的美妆工坊 | 房间3 | 循环 | 正向',
    'BGM_Plot_4_1_Room3Loop_Transmit_Reverse_100_4_4.wav': '副本·缇米丝的美妆工坊 | 房间3 | 循环 | 反向',
    'BGM_Plot_4_1_Room5Intro_100_4_4.wav': '副本·缇米丝的美妆工坊 | 房间5 | 开场',
    'BGM_Plot_4_1_Room5Loop_100_4_4.wav': '副本·缇米丝的美妆工坊 | 房间5 | 循环',
    'BGM_Plot_4_2_Room0_100_4_4.wav': '副本·古铸剑遗址 | 房间0',
    'BGM_Plot_4_2_Room1_100_4_4.wav': '副本·古铸剑遗址 | 房间1',
    'BGM_Plot_4_2_Room1_Silence_100_4_4.wav': '副本·古铸剑遗址 | 房间1 | 安静',
    'BGM_Plot_4_2_Room2_114_4_4.wav': '副本·古铸剑遗址 | 房间2',
    'BGM_Plot_4_2_Room3_100_4_4.wav': '副本·古铸剑遗址 | 房间3',
    'BGM_Plot_4_2_Room4_P1_Silence_154_3_4.wav': '副本·古铸剑遗址 | 房间4 | P1 | 安静',
    'BGM_Plot_4_2_Room4_P2_NoChoir_154_3_4.wav': '副本·古铸剑遗址 | 房间4 | P2 | 无合唱',
    'BGM_Plot_4_2_Room4_P3_Choir_154_3_4.wav': '副本·古铸剑遗址 | 房间4 | P3 | 合唱',
    'BGM_Plot_4_2_Room5_136_4_4.wav': '副本·古铸剑遗址 | 房间5',
    'BGM_Plot_4_2_Room5_Battle_82_4_4.wav': '副本·古铸剑遗址 | 房间5 | 战斗',
    'BGM_Plot_Prologue_1_HeavenPark_Demo_Loop_Cut2_BPM132.wav': '副本·无题之地 | 房间1 | 神息花园 | 演示 | 循环',
    'BGM_Plot_Prologue_1_HeavenPark_Loop.wav': '副本·无题之地 | 房间1 | 神息花园 | 循环',
    'BGM_Plot_Prologue_1_HeavenPark_OneShot.wav': '副本·无题之地 | 房间1 | 神息花园 | 单次',
    'BGM_Plot_Prologue_2_Ruins_Intro.wav': '副本·旧搭配师协会遗址 | 房间2 | 开场',
    'BGM_Plot_Prologue_2_Ruins_Loop.wav': '副本·旧搭配师协会遗址 | 房间2 | 循环',
    'BGM_Plot_Prologue_3_StarterArea_Intro.wav': '副本·大世界 | 房间3 | 搭配师协会纪念旧址 | 开场',
    'BGM_Plot_Prologue_3_StarterArea_Loop.wav': '副本·大世界 | 房间3 | 搭配师协会纪念旧址 | 循环',
    'BGM_Scene_ShiShuTian_Unpopulated_AncientVillage_Normal_Day_01_Sunny_bpm92_m44.wav': '石树田无人区 | 丰饶古村 | 白天 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_AncientVillage_Normal_Day_02_Sunny_bpm83_m44.wav': '石树田无人区 | 丰饶古村 | 白天 | 02 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_AncientVillage_Normal_Night_01_Sunny_bpm84_m44.wav': '石树田无人区 | 丰饶古村 | 夜晚 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_AncientVillage_Normal_Night_02_Sunny_bpm80_m44.wav': '石树田无人区 | 丰饶古村 | 夜晚 | 02 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_AncientVillage_Storyline_Day_Sunny_bpm92_m44.wav': '石树田无人区 | 丰饶古村 | 剧情 | 白天 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_AncientVillage_Storyline_Night_Sunny_bpm83_m44.wav': '石树田无人区 | 丰饶古村 | 剧情 | 夜晚 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_FarmRockTree_Day_01_Sunny_bpm100_m34.wav': '石树田无人区 | 麦浪农场 | 白天 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_FarmRockTree_Day_02_Sunny_bpm125_m44.wav': '石树田无人区 | 麦浪农场 | 白天 | 02 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_FarmRockTree_Night_01_Sunny_bpm120_m34.wav': '石树田无人区 | 麦浪农场 | 夜晚 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_FarmRockTree_Night_02_Sunny_bpm95_m44.wav': '石树田无人区 | 麦浪农场 | 夜晚 | 02 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_Glide_Day_01_Sunny_bpm126_m44.wav': '石树田无人区 | 空中通路 | 白天 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_Glide_Day_02_Sunny_bpm145_m34.wav': '石树田无人区 | 空中通路 | 白天 | 02 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_HootingStation_Normal_Day_01_Sunny_bpm100_m44.wav': '石树田无人区 | 呜呜车站 | 白天 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_HootingStation_Normal_Day_02_bpm130_m44.wav': '石树田无人区 | 呜呜车站 | 白天 | 02 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_HootingStation_Normal_Night _01_bpm90_m44.wav': '石树田无人区 | 呜呜车站 | 夜晚 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_HootingStation_Normal_Night _02_Sunny_bpm120_m44.wav': '石树田无人区 | 呜呜车站 | 夜晚 | 02 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_HootingStation_Stoyline_Day_01_bpm80_m44.wav': '石树田无人区 | 呜呜车站 | 剧情 | 白天',
    'BGM_Scene_ShiShuTian_Unpopulated_HootingStation_Stoyline_Night_01_bpm70_m44.wav': '石树田无人区 | 呜呜车站 | 剧情 | 夜晚',
    'BGM_Scene_ShiShuTian_Unpopulated_JoyfulMarket_Normal_Day_01_bpm88_m44.wav': '石树田无人区 | 欢乐市集 | 白天 | 01',
    'BGM_Scene_ShiShuTian_Unpopulated_JoyfulMarket_Normal_Day_02_Sunny_bpm62_m44.wav': '石树田无人区 | 欢乐市集 | 白天 | 02 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_JoyfulMarket_Normal_Night_01_bpm88_m44.wav': '石树田无人区 | 欢乐市集 | 夜晚 | 01',
    'BGM_Scene_ShiShuTian_Unpopulated_JoyfulMarket_Normal_Night_02_bpm62_m44.wav': '石树田无人区 | 欢乐市集 | 夜晚 | 02',
    'BGM_Scene_ShiShuTian_Unpopulated_JoyfulMarket_StoryLine_Day_01_bpm120_m44.wav': '石树田无人区 | 欢乐市集 | 剧情 | 白天',
    'BGM_Scene_ShiShuTian_Unpopulated_JoyfulMarket_StoryLine_Night_01_bpm108_m44.wav': '石树田无人区 | 欢乐市集 | 剧情 | 夜晚',
    'BGM_Scene_ShiShuTian_Unpopulated_RippleManor_Day_01_Sunny_bpm70_m44.wav': '石树田无人区 | 涟漪庄园 | 白天 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_RippleManor_Day_02_Sunny_bpm70_m44.wav': '石树田无人区 | 涟漪庄园 | 白天 | 02 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_RippleManor_Night_01_Sunny_bpm55_m44.wav': '石树田无人区 | 涟漪庄园 | 夜晚 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_RippleManor_Night_02_Sunny_bpm58_m44.wav': '石树田无人区 | 涟漪庄园 | 夜晚 | 02 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_RockCrown_Normal_Day_01_bpm86_m44.wav': '石树田无人区 | 石之冠 | 白天 | 01',
    'BGM_Scene_ShiShuTian_Unpopulated_RockCrown_Normal_Day_02_bpm71_m44.wav': '石树田无人区 | 石之冠 | 白天 | 02',
    'BGM_Scene_ShiShuTian_Unpopulated_RockCrown_Normal_Night_01_bpm82_m44.wav': '石树田无人区 | 石之冠 | 夜晚 | 01',
    'BGM_Scene_ShiShuTian_Unpopulated_RockCrown_Normal_Night_02_bpm62_m44.wav': '石树田无人区 | 石之冠 | 夜晚 | 02',
    'BGM_Scene_ShiShuTian_Unpopulated_RockCrown_Storyline_Day_01_bpm102_m44.wav': '石树田无人区 | 石之冠 | 剧情 | 白天',
    'BGM_Scene_ShiShuTian_Unpopulated_RockCrown_Storyline_Night_01_Sunny_bpm95_m44.wav': '石树田无人区 | 石之冠 | 剧情 | 夜晚 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_WaterspoutGlide_Day_01_Sunny_bpm126_m44.wav': '石树田无人区 | 水龙卷·空中通路 | 白天 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_WaterspoutGlide_Day_02_Sunny_bpm115_m44.wav': '石树田无人区 | 水龙卷·空中通路 | 白天 | 02 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_Wild_Luoshishan_Day_01_sunny_bpm72_m68.wav': '石树田无人区 | 落石山 | 白天 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_Wild_Luoshishan_Night_01_Sunny_bpm60_m68.wav': '石树田无人区 | 落石山 | 夜晚 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_Windmill_Day_01_Sunny_bpm110_m34.wav': '石树田无人区 | 乘风磨坊 | 白天 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_Windmill_Day_02_Sunny_bpm110_m34.wav': '石树田无人区 | 乘风磨坊 | 白天 | 02 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_Windmill_Night_01_Sunny_bpm100_m34.wav': '石树田无人区 | 乘风磨坊 | 夜晚 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Unpopulated_Windmill_Normal_Night_02_bpm60_m44.wav': '石树田无人区 | 乘风磨坊 | 夜晚 | 02',
    'BGM_Scene_ShiShuTian_Village_HuatianCunzhuang_Day_100_4_4_Loop.wav': '小石树田村 | 紫穗草花田 | 白天 | 循环',
    'BGM_Scene_ShiShuTian_Village_HuatianCunzhuang_Day_To_Night.wav': '小石树田村 | 紫穗草花田 | 白天到夜晚',
    'BGM_Scene_ShiShuTian_Village_HuatianCunzhuang_Night_90_3_4_Loop.wav': '小石树田村 | 紫穗草花田 | 夜晚 | 循环',
    'BGM_Scene_ShiShuTian_Village_HuatianCunzhuang_Night_To_Day.wav': '小石树田村 | 紫穗草花田 | 夜晚到白天',
    'BGM_Scene_ShiShuTian_Village_Market_Day_bpm67_m44.wav': '小石树田村 | 村口集市 | 白天',
    'BGM_Scene_ShiShuTian_Village_Market_Night_noGTR_bpm67_m44.wav': '小石树田村 | 村口集市 | 夜晚 | 无吉他',
    'BGM_Scene_ShiShuTian_Village_Weaving_WorkShop_Day_01_Sunny_98_m128.wav': '小石树田村 | 染织工坊 | 白天 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Village_Weaving_Workshop_Night_01_Sunny_62_m68.wav': '小石树田村 | 染织工坊 | 夜晚 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Wild_JuMinQu_Day_01_sunny_72_6_8.wav': '小石树田村 | 野外&居民区 | 白天 | 01 | 晴天',
    'BGM_Scene_ShiShuTian_Wild_JuMinQu_Night_01_sunny_60_6_8.wav': '小石树田村 | 野外&居民区 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_BadWishesHill_Day_01_Sunny_bpm90_ChangeTimeSignature.wav': '怪味愿望山坡 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_BadWishesHill_Day_02_Sunny_bpm100_m44.wav': '怪味愿望山坡 | 白天 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_BadWishesHill_Night_01_Sunny_bpm53_m44.wav': '怪味愿望山坡 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_BadWishesHill_Night_02_Sunny_bpm100_m44.wav': '怪味愿望山坡 | 夜晚 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_CelebrationCenter_Night_01_Vox_Sunny_bpm63_m44.wav': '心愿庆典管理处 | 夜晚 | 01 | 有人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_CelebrationCenter_Night_02_Vox_Sunny_bpm62_m44.wav': '心愿庆典管理处 | 夜晚 | 02 | 有人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_ChigdaCavePrison.wav': '监禁洞窟',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Night_01_noVox_Sunny_bpm63_m44.wav': '金蔷薇花谷 | 夜晚 | 01 | 无人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Night_02_noVox_Sunny_bpm62_m44.wav': '金蔷薇花谷 | 夜晚 | 02 | 无人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Normal_Day_01_noVox_Sunny_bpm75_m68.wav': '金蔷薇花谷 | 白天 | 01 | 无人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Normal_Day_01_Sunny_bpm75_m68.wav': '金蔷薇花谷 | 白天 | 01 | 有人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Normal_Day_02_noVox_Sunny_bpm87_m44.wav': '金蔷薇花谷 | 白天 | 02 | 无人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Normal_Day_02_Sunny_bpm87_m44.wav': '金蔷薇花谷 | 白天 | 02 | 有人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GoldenRosesValley_Storyline_Day_01_Sunny_bpm80_m44.wav': '金蔷薇花谷 | 剧情 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_GuardsGarrison_Day_01_Sunny_bpm102_m44.wav': '千愿巨树·近卫队驻地 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_GuardsGarrison_Day_02_Sunny_bpm86_m44.wav': '千愿巨树·近卫队驻地 | 白天 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_GuardsGarrison_Night_01_Sunny_bpm68_m44.wav': '千愿巨树·近卫队驻地 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_GuardsGarrison_Night_02_bpm86_m44.wav': '千愿巨树·近卫队驻地 | 夜晚 | 02',
    'BGM_Scene_Qiyuanshulin_GT_Living_Day_01_Sunny_bpm102_m44.wav': '千愿巨树·居民区 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Living_Day_02_Sunny_bpm86_m44.wav': '千愿巨树·居民区 | 白天 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Living_Gtr_Night_01_Sunny_bpm68_m44_v2.wav': '千愿巨树·居民区 | 夜晚 | 01 | 有吉他 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Living_Night_02_bpm86_m44.wav': '千愿巨树·居民区 | 夜晚 | 02',
    'BGM_Scene_Qiyuanshulin_GT_Living_Vox_Night_01_Sunny_bpm68_m44_v2.wav': '千愿巨树·居民区 | 夜晚 | 01 | 有人声 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_River_Night_01_Sunny_bpm68_m44.wav': '千愿巨树·巨树浅滩 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Normal_Day_02_Sunny_bpm86_m44.wav': '千愿巨树·心愿圣殿 | 白天 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Normal_Night_01_bpm68_m44.wav': '千愿巨树·心愿圣殿 | 夜晚 | 01',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Normal_Night_02_bpm86_m44.wav': '千愿巨树·心愿圣殿 | 夜晚 | 02',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Storyline_Day_01_Sunny_bpm102_m44_v2.wav': '千愿巨树·心愿圣殿 | 剧情 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Storyline_Day_02_bpm86_m44.wav': '千愿巨树·心愿圣殿 | 剧情 | 白天 | 02',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Storyline_Day_Sunny_bpm102_m44.wav': '千愿巨树·心愿圣殿 | 剧情 | 白天 | 晴天',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Storyline_Night_01_bpm68_m44.wav': '千愿巨树·心愿圣殿 | 剧情 | 夜晚 | 01',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Storyline_Night_02_bpm86_m44.wav': '千愿巨树·心愿圣殿 | 剧情 | 夜晚 | 02',
    'BGM_Scene_Qiyuanshulin_QCCenter_Day_01_Sunny_bpm134_m34.wav': '愿望质检中心 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_QCnRND_Night_01_Sunny_bpm100_m34.wav': '愿望质检中心&心愿研发所 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_RiverCanyon_Day_01_bpm112_m44.wav': '古木河畔 | 白天 | 01',
    'BGM_Scene_Qiyuanshulin_RiverCanyon_Night_01_Sunny_bpm86_m44.wav': '古木河畔 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_River_Day_01_bpm102_m44.wav': '河畔 | 白天 | 01',
    'BGM_Scene_Qiyuanshulin_River_Day_02_bpm86_m44.wav': '河畔 | 白天 | 02',
    'BGM_Scene_Qiyuanshulin_River_Night_02_bpm86_m44.wav': '河畔 | 夜晚 | 02',
    'BGM_Scene_Qiyuanshulin_RNDInstitute_Day_01_Sunny_bpm134_m34.wav': '心愿研发所 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_SwordFoundry_Day_01_Sunny_bpm120_m44.wav': '古铸剑遗址 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_SwordFoundry_Day_02_Sunny_bpm120_m44.wav': '古铸剑遗址 | 白天 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_SwordFoundry_Night_01_Sunny_bpm120_m44.wav': '古铸剑遗址 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_SwordFoundry_Night_02_Sunny_bpm120_m44.wav': '古铸剑遗址 | 夜晚 | 02 | 晴天',
    'BGM_Scene_Qiyuanshulin_TimisBeautyFactory_Day_01_bpm124_m14.wav': '缇米丝的美妆工坊 | 白天 | 01',
    'BGM_Scene_Qiyuanshulin_TimisBeautyFactory_Night_01_bpm124_m44.wav': '缇米丝的美妆工坊 | 夜晚 | 01',
    'BGM_Scene_Qiyuanshulin_VanishingStarland_Day_01_Sunny_bpm94_m34.wav': '星没之地 | 白天 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_VanishingStarland_Night_01_Sunny_bpm85_m34.wav': '星没之地 | 夜晚 | 01 | 晴天',
    'BGM_Scene_Qiyuanshulin_VisaCave_bpm65_m44.wav': '心愿通行许可处 | 洞窟内',
    'BGM_QiYuanShuLin_LegendAnimal_CharmingFox_Clean.wav': '传奇生灵·曦光狐 | 已清洁',
    'BGM_QiYuanShuLin_LegendAnimal_CharmingFox_Dirty.wav': '传奇生灵·曦光狐 | 未清洁',
    'BGM_Scene_Qiyuanshulin_GT_Sanctuary_Indoor_Sunny_bpm57_m44.wav': '千愿巨树·心愿圣殿 | 室内 | 晴天',
    'BGM_Scene_Qiyuanshulin_QCCenter_Indoor_bpm130_m34.wav': '愿望质检中心 | 室内',
    'BGM_Scene_Housing_Indoor_01_bpm72_m44.wav': '',
    'BGM_Scene_Housing_LivingArea_Day_01_Sunny_bpm100_m44.wav': '',
    'BGM_Scene_Housing_LivingArea_Night_01_Sunny_bpm75_m44.wav': '',
    'BGM_Scene_Housing_PlayingArea_Day_01_Sunny_bpm100_m44.wav': '',
    'BGM_Scene_Housing_PlayingArea_Night_01_Sunny_bpm75_m44.wav': '',
    'BGM_scene_rainbow_01_day_bpm115_3_4 V5.wav': '',
    'BGM_scene_map01_HuoBanJie_day_01_bpm115_4_4.wav': '伙伴节 | 白天 | 01',
    'BGM_Scene_Map01_HuoBanJie_Night_118BPM.wav': '伙伴节 | 夜晚',
    'SingingBlueDragon_HarpShow_.wav': '唱诗蓝龙 | 竖琴表演',
    'SingingBlueDragon_Short_1.wav': '唱诗蓝龙 | 短1',
    'SingingBlueDragon_Short_2.wav': '唱诗蓝龙 | 短2',
    'SingingBlueDragon_Short_3.wav': '唱诗蓝龙 | 短3',
    'SingingBlueDragon_Short_4.wav': '唱诗蓝龙 | 短4',
    'Bgm_CoolGuy_FittingRoom.wav': '帅气天王 | 试衣间中',
    'BGM_UI_Infinityheart_New_ChangeBPM.wav': '无限之心 | 新',
    'BGM_UI_Login_96_3_4_MixV1.wav': '登录 | 一测 | 混音V1',
    'Mirror_Challenge_UI.wav': '奇迹之冠 | UI',
    'TogetherTillInfinity_InProg7L2.Mstr.24.wav': '登录 | 公测',
    'BGM_UI_Login_CBT2_BinkVideo.wav': '登录 | 二测',
    'BGM_Boxgame_QiYuanShuLin_Wishball_Intro_ChangeBPM.wav': '',
    'BGM_Boxgame_QiYuanShuLin_Wishball_Lose_bpm110_m44.wav': '',
    'BGM_Boxgame_QiYuanShuLin_Wishball_Place_bpm110_m44.wav': '游戏·愿望球速达 | 放置阶段',
    'BGM_Boxgame_QiYuanShuLin_Wishball_Transport_bpm110_m44.wav': '游戏·愿望球速达 | 运输阶段',
    'BGM_Boxgame_QiYuanShuLin_Wishball_Win_bpm110_m44.wav': '',
    'BGM_Scene_ShiShuTian_Village_Market_Night_OnlyGTR_bpm67_m44.wav': '小石树田村 | 村口集市 | 夜晚 | 仅吉他',
}